# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aggregate_factor_model_params_cpp <- function(per_cohort_factor_estimates_xptrs, observed_outcome_indices, cohort_weights_xptr) {
    .Call(`_apm_aggregate_factor_model_params_cpp`, per_cohort_factor_estimates_xptrs, observed_outcome_indices, cohort_weights_xptr)
}

aggregate_factor_model_params_by_spec_cpp <- function(cohort_specific_factor_ests, observed_outcome_indices, cohort_weights_by_spec) {
    .Call(`_apm_aggregate_factor_model_params_by_spec_cpp`, cohort_specific_factor_ests, observed_outcome_indices, cohort_weights_by_spec)
}

#' Get the version of the apm library
#'
#' Returns a string containing the version number of the underlying C++ apm
#' library. This is useful for debugging and ensuring compatibility.
#'
#' @return A character string containing the library version (e.g., "0.1.0").
#' @examples
#' get_version()
#' @export
get_version <- function() {
    .Call(`_apm_get_version`)
}

#' Computes an aligned matrix of factor vectors from cohort-specific ones.
#'
#' This function constructs an Aggregated Projection Matrix (APM) from cohort-specific 
#' factor matrices and then returns an orthonormal basis for the null space of the APM, 
#' which also serves as a basis for the column space of the matrix whose rows are the 
#' factor vectors corresponding to each outcome.
#'
#' @param cohort_factor_matrices A list of matrices, one for each cohort, 
#' where the rows of the matrix corresponding to a given cohort contain the factor vectors for the observed outcomes for that cohort.
#' Each matrix must have the same number of columns, equal to the rank of the factor model.
#' @param observed_outcome_indices A list of integer vectors of the same length
#'   as cohort_factor_matrices. Each vector contains the 1-based indices
#'   indicating which outcomes were observed for the corresponding cohort. The number of indices
#'   must match the number of rows in the cohort's factor matrix.
#' @param cohort_weights An optional numeric vector of weights for each cohort.
#'   If not provided, cohorts are weighted equally. The weights are scaled to 
#'   sum to one.
#' @return A matrix whose columns form an orthonormal basis for the null space
#'         of the aggregated projection matrix.
#' @export
align_factors_using_apm <- function(cohort_factor_matrices, observed_outcome_indices, cohort_weights = NULL) {
    .Call(`_apm_align_factors_using_apm`, cohort_factor_matrices, observed_outcome_indices, cohort_weights)
}

#' Constructs the weighted aggregated projection matrix used by APM.
#'
#' Builds sum_c w_c (I_T - P_c), where P_c is the projection onto the span of
#' the cohort-specific factors padded to T rows. Weights default to equal across
#' cohorts when omitted, must be nonnegative, and are normalized to sum to 1.
#'
#' @param cohort_factor_matrices A list of matrices, one per cohort. Each matrix has
#'   rows corresponding to observed outcomes for that cohort and the same number of
#'   columns r across cohorts.
#' @param observed_outcome_indices A list of integer vectors (1-based indices) indicating
#'   which outcomes were observed for each cohort. Each vector's length must match the
#'   number of rows of the corresponding factor matrix.
#' @param cohort_weights Optional numeric vector of length C with cohort weights.
#'   If omitted, cohorts are weighted equally. Weights are normalized to sum to 1.
#' @return A T x T numeric matrix representing the aggregated projection matrix.
#' @export
compute_aggregated_projection_matrix <- function(cohort_factor_matrices, observed_outcome_indices, cohort_weights = NULL) {
    .Call(`_apm_compute_aggregated_projection_matrix`, cohort_factor_matrices, observed_outcome_indices, cohort_weights)
}

#' Aggregates cohort-specific covariate coefficient estimates.
#'
#' This function takes a vector of cohort-specific covariate coefficient estimates
#' and returns their average.
#'
#' @param a_c_vec A list of numeric vectors, where each vector contains cohort-specific
#'   covariate coefficient estimates.
#' @return A numeric vector containing the aggregated covariate coefficient estimates.
#' @export
aggregate_cohort_specific_covariate_coefs <- function(a_c_vec) {
    .Call(`_apm_aggregate_cohort_specific_covariate_coefs`, a_c_vec)
}

#' Aggregates cohort-specific outcome fixed effect estimates.
#'
#' This function computes the average of outcome fixed effect estimates across cohorts
#' for each outcome.
#'
#' @param g_0_c_vec A list of numeric vectors, where each vector contains cohort-specific estimates of outcome
#'   fixed effects for the observed outcomes in those cohorts.
#' @param observed_outcome_indices A list of integer vectors, where each
#'   vector contains the 1-based indices of observed outcomes for a cohort.
#' @return A numeric vector containing the aggregated outcome fixed effect
#'   estimates for all outcomes.
#' @export
aggregate_cohort_specific_outcome_fes <- function(g_0_c_vec, observed_outcome_indices) {
    .Call(`_apm_aggregate_cohort_specific_outcome_fes`, g_0_c_vec, observed_outcome_indices)
}

#' Impute all outcomes for a single cohort from its observed outcome means.
#'
#' Given factors G and observed outcome means m_c for a cohort, computes the
#' implied mean outcomes for all T outcomes by estimating the cohort's loading
#' and applying the factor model.
#'
#' @param G A T x r matrix of estimated factors.
#' @param T_c A vector of 1-based indices indicating which outcomes the cohort observes.
#' @param m_c A vector containing the observed outcome means for the cohort (length matches T_c).
#' @param g_0 Optional T-dimensional vector of estimated outcome fixed effects.
#' @param a Optional q-dimensional vector of estimated covariate coefficients.
#' @param X_c Optional T x q matrix of covariate means for the cohort.
#' @return A T-dimensional vector of imputed outcome means.
#' @export
impute_outcomes_from_obs_outcomes <- function(G, T_c, m_c, g_0 = NULL, a = NULL, X_c = NULL) {
    .Call(`_apm_impute_outcomes_from_obs_outcomes`, G, T_c, m_c, g_0, a, X_c)
}

#' Estimates mean outcomes for each cohort.
#'
#' This function supports various combinations of factors, fixed effects, and covariates.
#'
#' @param G A T x r matrix whose rows are estimated factor vectors.
#' @param observed_outcome_indices A list where each element is a vector of 
#'                                 1-based indices for the observed outcomes for a cohort.
#' @param m_c_vec A list of numeric vectors, where each vector m_c contains the 
#'                observed outcomes for a cohort.
#' @param g_0 An optional T-dimensional vector of estimated outcome fixed effects.
#' @param a An optional q-dimensional vector of estimated covariate coefficients.
#' @param X_c_vec An optional list of T x q matrices, where each matrix X_c contains the average values of q covariates for each outcome within a cohort.
#' @return A C x T matrix where each row c contains the estimated T mean outcomes for cohort c.
#' @export
impute_outcomes_across_cohorts_from_obs_outcomes <- function(G, observed_outcome_indices, m_c_vec, g_0 = NULL, a = NULL, X_c_vec = NULL) {
    .Call(`_apm_impute_outcomes_across_cohorts_from_obs_outcomes`, G, observed_outcome_indices, m_c_vec, g_0, a, X_c_vec)
}

#' Implements the Observed Outcome Overlap (O^3) algorithm to assess factor identification.
#'
#' This function iteratively groups cohorts based on the overlap of their
#' observed outcomes. Two super cohorts are merged if the number of their
#' shared outcomes meets or exceeds the model rank, `r`. The process
#' continues until no more cohorts can be merged.
#'
#' @param observed_outcome_indices A list of integer vectors, where each
#'   vector contains the 1-based indices corresponding to the observed outcomes for a cohort.
#' @param r The model rank, used as the minimum overlap threshold for merging cohorts.
#' @return A list of lists of sets, representing the super cohorts at each
#'   iteration of the algorithm. Each list of super cohorts is a list of integer vectors
#'   corresponding to the original cohorts together forming a super cohort.
#' @export
o3_algorithm <- function(observed_outcome_indices, r) {
    .Call(`_apm_o3_algorithm`, observed_outcome_indices, r)
}

#' Impute outcomes across cohorts using factors and cohort mean loadings (L)
#'
#' Supports optional fixed effects (g_0) and covariates (a, X_c list).
#'
#' @param G A T x r matrix of factor scores.
#' @param L A C x r matrix of cohort mean loadings.
#' @param g_0 Optional T-vector of outcome fixed effects.
#' @param a Optional q-vector of covariate coefficients. Requires X_c.
#' @param X_c Optional list of T x q matrices, one per cohort (required if a is provided).
#' @return A C x T matrix where row c contains imputed outcomes for cohort c.
#' @export
impute_outcomes_across_cohorts <- function(G, L, g_0 = NULL, a = NULL, X_c = NULL) {
    .Call(`_apm_impute_outcomes_across_cohorts`, G, L, g_0, a, X_c)
}

get_weighted_bootstrap_ptr_cpp <- function(N, B, type, seed = NULL) {
    .Call(`_apm_get_weighted_bootstrap_ptr_cpp`, N, B, type, seed)
}

wb_n_obs_cpp <- function(xp) {
    .Call(`_apm_wb_n_obs_cpp`, xp)
}

wb_n_bootstraps_cpp <- function(xp) {
    .Call(`_apm_wb_n_bootstraps_cpp`, xp)
}

wb_draw_cpp <- function(xp, b) {
    .Call(`_apm_wb_draw_cpp`, xp, b)
}

wb_obs_cpp <- function(xp, i) {
    .Call(`_apm_wb_obs_cpp`, xp, i)
}

wb_obs_rows_cpp <- function(xp, idx) {
    .Call(`_apm_wb_obs_rows_cpp`, xp, idx)
}

wb_weights_cpp <- function(xp) {
    .Call(`_apm_wb_weights_cpp`, xp)
}

get_bootstrap_inference_cpp <- function(point_ests, bootstrap_replicates, N, sig_level = 0.05) {
    .Call(`_apm_get_bootstrap_inference_cpp`, point_ests, bootstrap_replicates, N, sig_level)
}

sir_point_cpp <- function(xp) {
    .Call(`_apm_sir_point_cpp`, xp)
}

sir_pointwise_t_cpp <- function(xp) {
    .Call(`_apm_sir_pointwise_t_cpp`, xp)
}

sir_pointwise_p_cpp <- function(xp) {
    .Call(`_apm_sir_pointwise_p_cpp`, xp)
}

sir_std_error_cpp <- function(xp) {
    .Call(`_apm_sir_std_error_cpp`, xp)
}

sir_sig_level_cpp <- function(xp) {
    .Call(`_apm_sir_sig_level_cpp`, xp)
}

sir_ci_lb_cpp <- function(xp) {
    .Call(`_apm_sir_ci_lb_cpp`, xp)
}

sir_ci_ub_cpp <- function(xp) {
    .Call(`_apm_sir_ci_ub_cpp`, xp)
}

sir_fwer_control_p_cpp <- function(xp) {
    .Call(`_apm_sir_fwer_control_p_cpp`, xp)
}

sir_cb_lb_cpp <- function(xp) {
    .Call(`_apm_sir_cb_lb_cpp`, xp)
}

sir_cb_ub_cpp <- function(xp) {
    .Call(`_apm_sir_cb_ub_cpp`, xp)
}

cwe_has_bootstrap_cpp <- function(xp) {
    .Call(`_apm_cwe_has_bootstrap_cpp`, xp)
}

cwe_num_bootstrap_cpp <- function(xp) {
    .Call(`_apm_cwe_num_bootstrap_cpp`, xp)
}

cwe_point_weights_cpp <- function(xp) {
    .Call(`_apm_cwe_point_weights_cpp`, xp)
}

cwe_boot_weights_cpp <- function(xp, b) {
    .Call(`_apm_cwe_boot_weights_cpp`, xp, b)
}

build_R_panel_holder_cpp <- function(processed_panel, observed_outcome_indices, outcome_value_col, covar_cols, auxiliary_cols, num_units_in = NULL) {
    .Call(`_apm_build_R_panel_holder_cpp`, processed_panel, observed_outcome_indices, outcome_value_col, covar_cols, auxiliary_cols, num_units_in)
}

est_cohort_specific_params_from_panel_cpp <- function(panel_holder_xptr, est_specs, bootstrap_xptr = NULL, num_threads_in = NULL, cohort_outcomes_to_mask_in = NULL) {
    .Call(`_apm_est_cohort_specific_params_from_panel_cpp`, panel_holder_xptr, est_specs, bootstrap_xptr, num_threads_in, cohort_outcomes_to_mask_in)
}

est_masked_outcome_mean_err_metrics_cpp <- function(comps_list) {
    .Call(`_apm_est_masked_outcome_mean_err_metrics_cpp`, comps_list)
}

estimate_outcome_means_across_cohorts_cpp <- function(factor_model_estimates_xptr, observed_outcome_indices, suff_stat_estimates_xptrs) {
    .Call(`_apm_estimate_outcome_means_across_cohorts_cpp`, factor_model_estimates_xptr, observed_outcome_indices, suff_stat_estimates_xptrs)
}

estimate_outcome_means_across_cohorts_by_spec_cpp <- function(factor_model_estimates_by_spec, observed_outcome_indices, suff_stat_estimates_xptrs) {
    .Call(`_apm_estimate_outcome_means_across_cohorts_by_spec_cpp`, factor_model_estimates_by_spec, observed_outcome_indices, suff_stat_estimates_xptrs)
}

#' Get the default C++ concurrency level
#'
#' Returns the default number of threads used by the C++ backend for parallel
#' computations. This value is typically determined by the oneTBB library
#' and corresponds to the number of hardware threads available on the system.
#'
#' @return An integer indicating the default number of threads for C++
#'   parallel operations.
#' @seealso \code{\link{set_apm_threads}} for setting the number of threads.
#' @examples
#' get_cpp_default_concurrency()
#' @export
get_cpp_default_concurrency <- function() {
    .Call(`_apm_get_cpp_default_concurrency`)
}

make_factor_model_estimates_cpp <- function(G, g0 = NULL, a = NULL, B = 0L) {
    .Call(`_apm_make_factor_model_estimates_cpp`, G, g0, a, B)
}

make_outcome_mean_suff_stat_estimates_cpp <- function(observed_means, covar_means = NULL, B = 0L) {
    .Call(`_apm_make_outcome_mean_suff_stat_estimates_cpp`, observed_means, covar_means, B)
}

make_cohort_weight_estimates_cpp <- function(cohort_weights, bootstrap_weights = NULL) {
    .Call(`_apm_make_cohort_weight_estimates_cpp`, cohort_weights, bootstrap_weights)
}

est_target_params_cpp <- function(ome_xptr, stats_xptrs_by_cohort, eta_xptrs_by_cohort, r_fn) {
    .Call(`_apm_est_target_params_cpp`, ome_xptr, stats_xptrs_by_cohort, eta_xptrs_by_cohort, r_fn)
}

tpe_has_bootstrap_cpp <- function(xp_) {
    .Call(`_apm_tpe_has_bootstrap_cpp`, xp_)
}

tpe_num_bootstrap_cpp <- function(xp_) {
    .Call(`_apm_tpe_num_bootstrap_cpp`, xp_)
}

tpe_p_cpp <- function(xp_) {
    .Call(`_apm_tpe_p_cpp`, xp_)
}

tpe_point_params_cpp <- function(xp_) {
    .Call(`_apm_tpe_point_params_cpp`, xp_)
}

tpe_boot_params_cpp <- function(xp_, b1) {
    .Call(`_apm_tpe_boot_params_cpp`, xp_, b1)
}

tpe_boot_params_matrix_cpp <- function(xp_) {
    .Call(`_apm_tpe_boot_params_matrix_cpp`, xp_)
}

est_target_params_by_spec_cpp <- function(ome_by_spec, stats_xptrs_by_cohort, eta_xptrs_by_cohort, r_fn) {
    .Call(`_apm_est_target_params_by_spec_cpp`, ome_by_spec, stats_xptrs_by_cohort, eta_xptrs_by_cohort, r_fn)
}

get_target_param_diff_ests_cpp <- function(tpe1_xp, tpe2_xp) {
    .Call(`_apm_get_target_param_diff_ests_cpp`, tpe1_xp, tpe2_xp)
}

combine_target_param_ests_cpp <- function(tpe1_xp, tpe2_xp) {
    .Call(`_apm_combine_target_param_ests_cpp`, tpe1_xp, tpe2_xp)
}

combine_target_param_ests_multi_cpp <- function(tpe_list) {
    .Call(`_apm_combine_target_param_ests_multi_cpp`, tpe_list)
}

subset_target_param_ests_cpp <- function(tpe_xp, indices_0based) {
    .Call(`_apm_subset_target_param_ests_cpp`, tpe_xp, indices_0based)
}

est_target_param_components_from_panel_cpp <- function(panel_holder_xptr, est_specs, bootstrap_xptr = NULL, num_threads_in = NULL, cohort_outcomes_to_mask_in = NULL, est_outcome_means_via_imputation = TRUE, imputation_options_in = NULL) {
    .Call(`_apm_est_target_param_components_from_panel_cpp`, panel_holder_xptr, est_specs, bootstrap_xptr, num_threads_in, cohort_outcomes_to_mask_in, est_outcome_means_via_imputation, imputation_options_in)
}

target_param_inference_cpp <- function(tpe_xptr, panel_holder_xptr, sig_level = 0.05) {
    .Call(`_apm_target_param_inference_cpp`, tpe_xptr, panel_holder_xptr, sig_level)
}

target_param_inference_by_spec_cpp <- function(tpe_by_spec, panel_holder_xptr, sig_level = 0.05) {
    .Call(`_apm_target_param_inference_by_spec_cpp`, tpe_by_spec, panel_holder_xptr, sig_level)
}

estimator_add_data_cpp <- function(xp, unit_idxs_1based, Y, X = NULL) {
    invisible(.Call(`_apm_estimator_add_data_cpp`, xp, unit_idxs_1based, Y, X))
}

estimator_add_datum_cpp <- function(xp, unit_idx_1based, Y, X = NULL) {
    invisible(.Call(`_apm_estimator_add_datum_cpp`, xp, unit_idx_1based, Y, X))
}

estimator_r_cpp <- function(xp) {
    .Call(`_apm_estimator_r_cpp`, xp)
}

estimator_Tc_cpp <- function(xp) {
    .Call(`_apm_estimator_Tc_cpp`, xp)
}

estimator_q_cpp <- function(xp) {
    .Call(`_apm_estimator_q_cpp`, xp)
}

estimator_B_cpp <- function(xp) {
    .Call(`_apm_estimator_B_cpp`, xp)
}

estimator_estimate_cpp <- function(xp) {
    .Call(`_apm_estimator_estimate_cpp`, xp)
}

fme_has_bootstrap_cpp <- function(fme) {
    .Call(`_apm_fme_has_bootstrap_cpp`, fme)
}

fme_num_bootstrap_cpp <- function(fme) {
    .Call(`_apm_fme_num_bootstrap_cpp`, fme)
}

fme_has_g0_cpp <- function(fme) {
    .Call(`_apm_fme_has_g0_cpp`, fme)
}

fme_has_a_cpp <- function(fme) {
    .Call(`_apm_fme_has_a_cpp`, fme)
}

fme_point_G_cpp <- function(fme) {
    .Call(`_apm_fme_point_G_cpp`, fme)
}

fme_point_g0_cpp <- function(fme) {
    .Call(`_apm_fme_point_g0_cpp`, fme)
}

fme_point_a_cpp <- function(fme) {
    .Call(`_apm_fme_point_a_cpp`, fme)
}

fme_boot_G_cpp <- function(fme, b) {
    .Call(`_apm_fme_boot_G_cpp`, fme, b)
}

fme_boot_g0_cpp <- function(fme, b) {
    .Call(`_apm_fme_boot_g0_cpp`, fme, b)
}

fme_boot_a_cpp <- function(fme, b) {
    .Call(`_apm_fme_boot_a_cpp`, fme, b)
}

fme_point_L_cpp <- function(fme) {
    .Call(`_apm_fme_point_L_cpp`, fme)
}

fme_boot_L_cpp <- function(fme, b) {
    .Call(`_apm_fme_boot_L_cpp`, fme, b)
}

est_fgw_bipartite_match_outcome_diff_params_multi_cpp <- function(ome_xptr, stats_xptrs_by_cohort, outcome_indices_1, outcome_indices_2, observed_outcome_indices_list, outcome_weights = NULL, use_observed_outcome_means = TRUE) {
    .Call(`_apm_est_fgw_bipartite_match_outcome_diff_params_multi_cpp`, ome_xptr, stats_xptrs_by_cohort, outcome_indices_1, outcome_indices_2, observed_outcome_indices_list, outcome_weights, use_observed_outcome_means)
}

est_fgw_bipartite_match_outcome_diff_params_cpp <- function(ome_xptr, stats_xptrs_by_cohort, outcome_idx_1, outcome_idx_2, observed_outcome_indices_list, use_observed_outcome_means = TRUE) {
    .Call(`_apm_est_fgw_bipartite_match_outcome_diff_params_cpp`, ome_xptr, stats_xptrs_by_cohort, outcome_idx_1, outcome_idx_2, observed_outcome_indices_list, use_observed_outcome_means)
}

est_fgw_bipartite_match_outcome_diff_params_by_spec_multi_cpp <- function(ome_by_spec, stats_xptrs_by_cohort, outcome_indices_1, outcome_indices_2, observed_outcome_indices_list, outcome_weights = NULL, use_observed_outcome_means = TRUE) {
    .Call(`_apm_est_fgw_bipartite_match_outcome_diff_params_by_spec_multi_cpp`, ome_by_spec, stats_xptrs_by_cohort, outcome_indices_1, outcome_indices_2, observed_outcome_indices_list, outcome_weights, use_observed_outcome_means)
}

est_fgw_bipartite_match_outcome_diff_params_by_spec_cpp <- function(ome_by_spec, stats_xptrs_by_cohort, outcome_idx_1, outcome_idx_2, observed_outcome_indices_list, use_observed_outcome_means = TRUE) {
    .Call(`_apm_est_fgw_bipartite_match_outcome_diff_params_by_spec_cpp`, ome_by_spec, stats_xptrs_by_cohort, outcome_idx_1, outcome_idx_2, observed_outcome_indices_list, use_observed_outcome_means)
}

est_avg_fgw_bipartite_match_outcome_diff_params_multi_cpp <- function(ome_xptr, stats_xptrs_by_cohort, outcome_groupings, observed_outcome_indices_list, outcome_weights = NULL, use_observed_outcome_means = TRUE, num_threads = 1L) {
    .Call(`_apm_est_avg_fgw_bipartite_match_outcome_diff_params_multi_cpp`, ome_xptr, stats_xptrs_by_cohort, outcome_groupings, observed_outcome_indices_list, outcome_weights, use_observed_outcome_means, num_threads)
}

est_avg_fgw_bipartite_match_outcome_diff_params_cpp <- function(ome_xptr, stats_xptrs_by_cohort, outcome_indices, observed_outcome_indices_list, outcome_weights = NULL, use_observed_outcome_means = TRUE, num_threads = 1L) {
    .Call(`_apm_est_avg_fgw_bipartite_match_outcome_diff_params_cpp`, ome_xptr, stats_xptrs_by_cohort, outcome_indices, observed_outcome_indices_list, outcome_weights, use_observed_outcome_means, num_threads)
}

est_avg_fgw_bipartite_match_outcome_diff_params_by_spec_multi_cpp <- function(ome_by_spec, stats_xptrs_by_cohort, outcome_groupings, observed_outcome_indices_list, outcome_weights = NULL, use_observed_outcome_means = TRUE, num_threads = 1L) {
    .Call(`_apm_est_avg_fgw_bipartite_match_outcome_diff_params_by_spec_multi_cpp`, ome_by_spec, stats_xptrs_by_cohort, outcome_groupings, observed_outcome_indices_list, outcome_weights, use_observed_outcome_means, num_threads)
}

est_avg_fgw_bipartite_match_outcome_diff_params_by_spec_cpp <- function(ome_by_spec, stats_xptrs_by_cohort, outcome_indices, observed_outcome_indices_list, outcome_weights = NULL, use_observed_outcome_means = TRUE, num_threads = 1L) {
    .Call(`_apm_est_avg_fgw_bipartite_match_outcome_diff_params_by_spec_cpp`, ome_by_spec, stats_xptrs_by_cohort, outcome_indices, observed_outcome_indices_list, outcome_weights, use_observed_outcome_means, num_threads)
}

caux_point_dims_cpp <- function(xp_) {
    .Call(`_apm_caux_point_dims_cpp`, xp_)
}

caux_point_aux_means_cpp <- function(xp_) {
    .Call(`_apm_caux_point_aux_means_cpp`, xp_)
}

caux_has_bootstrap_cpp <- function(xp_) {
    .Call(`_apm_caux_has_bootstrap_cpp`, xp_)
}

caux_num_bootstrap_cpp <- function(xp_) {
    .Call(`_apm_caux_num_bootstrap_cpp`, xp_)
}

caux_boot_aux_means_cpp <- function(xp_, b) {
    .Call(`_apm_caux_boot_aux_means_cpp`, xp_, b)
}

comp_outcome_clustering_cpp <- function(panel_holder_xptr, grid_size, k, n_inits_in = NULL, seed_in = NULL, num_threads_in = NULL) {
    .Call(`_apm_comp_outcome_clustering_cpp`, panel_holder_xptr, grid_size, k, n_inits_in, seed_in, num_threads_in)
}

comp_outcome_clusterings_cpp <- function(panel_holder_xptr, grid_size, min_k, max_k, n_inits_in = NULL, seed_in = NULL, num_threads_in = NULL) {
    .Call(`_apm_comp_outcome_clusterings_cpp`, panel_holder_xptr, grid_size, min_k, max_k, n_inits_in, seed_in, num_threads_in)
}

get_new_cohorts_from_combining_outcomes_cpp <- function(panel_holder_xptr, old_to_new_outcome_1b) {
    .Call(`_apm_get_new_cohorts_from_combining_outcomes_cpp`, panel_holder_xptr, old_to_new_outcome_1b)
}

comp_imputation_components_cpp <- function(panel_holder_xptr, factor_model_estimates_xptr, cohort_outcome_mean_suff_stat_ests = NULL, weighted_bootstrap_xptr = NULL, effective_observed_outcome_indices = NULL, imputation_options_in = NULL, num_threads_in = NULL) {
    .Call(`_apm_comp_imputation_components_cpp`, panel_holder_xptr, factor_model_estimates_xptr, cohort_outcome_mean_suff_stat_ests, weighted_bootstrap_xptr, effective_observed_outcome_indices, imputation_options_in, num_threads_in)
}

comp_imputation_components_by_spec_cpp <- function(panel_holder_xptr, factor_model_estimates_by_spec, cohort_outcome_mean_suff_stat_ests = NULL, weighted_bootstrap_xptr = NULL, effective_observed_outcome_indices = NULL, imputation_options_in = NULL, num_threads_in = NULL) {
    .Call(`_apm_comp_imputation_components_by_spec_cpp`, panel_holder_xptr, factor_model_estimates_by_spec, cohort_outcome_mean_suff_stat_ests, weighted_bootstrap_xptr, effective_observed_outcome_indices, imputation_options_in, num_threads_in)
}

outcome_mean_estimator_new_cpp <- function(T_c, wb_xptr = NULL, T = 0L, q = 0L) {
    .Call(`_apm_outcome_mean_estimator_new_cpp`, T_c, wb_xptr, T, q)
}

omsse_add_data_cpp <- function(xp, unit_idxs_1based, Y, X = NULL) {
    invisible(.Call(`_apm_omsse_add_data_cpp`, xp, unit_idxs_1based, Y, X))
}

omsse_add_datum_cpp <- function(xp, unit_idx_1based, Y, X = NULL) {
    invisible(.Call(`_apm_omsse_add_datum_cpp`, xp, unit_idx_1based, Y, X))
}

omsse_Tc_cpp <- function(xp) {
    .Call(`_apm_omsse_Tc_cpp`, xp)
}

omsse_T_cpp <- function(xp) {
    .Call(`_apm_omsse_T_cpp`, xp)
}

omsse_q_cpp <- function(xp) {
    .Call(`_apm_omsse_q_cpp`, xp)
}

omsse_B_cpp <- function(xp) {
    .Call(`_apm_omsse_B_cpp`, xp)
}

omsse_estimate_cpp <- function(xp) {
    .Call(`_apm_omsse_estimate_cpp`, xp)
}

omsse_estimate_with_total_cpp <- function(xp, total_units) {
    .Call(`_apm_omsse_estimate_with_total_cpp`, xp, total_units)
}

omsse_has_bootstrap_cpp <- function(xp) {
    .Call(`_apm_omsse_has_bootstrap_cpp`, xp)
}

omsse_num_bootstrap_cpp <- function(xp) {
    .Call(`_apm_omsse_num_bootstrap_cpp`, xp)
}

omsse_point_has_covar_means_cpp <- function(xp) {
    .Call(`_apm_omsse_point_has_covar_means_cpp`, xp)
}

omsse_point_Tc_cpp <- function(xp) {
    .Call(`_apm_omsse_point_Tc_cpp`, xp)
}

omsse_point_T_cpp <- function(xp) {
    .Call(`_apm_omsse_point_T_cpp`, xp)
}

omsse_point_q_cpp <- function(xp) {
    .Call(`_apm_omsse_point_q_cpp`, xp)
}

omsse_point_observed_means_cpp <- function(xp) {
    .Call(`_apm_omsse_point_observed_means_cpp`, xp)
}

omsse_point_covar_means_cpp <- function(xp) {
    .Call(`_apm_omsse_point_covar_means_cpp`, xp)
}

omsse_point_cohort_pop_share_cpp <- function(xp) {
    .Call(`_apm_omsse_point_cohort_pop_share_cpp`, xp)
}

omsse_boot_cohort_pop_share_cpp <- function(xp, b) {
    .Call(`_apm_omsse_boot_cohort_pop_share_cpp`, xp, b)
}

omsse_boot_observed_means_cpp <- function(xp, b) {
    .Call(`_apm_omsse_boot_observed_means_cpp`, xp, b)
}

omsse_boot_covar_means_cpp <- function(xp, b) {
    .Call(`_apm_omsse_boot_covar_means_cpp`, xp, b)
}

ome_has_bootstrap_cpp <- function(xp) {
    .Call(`_apm_ome_has_bootstrap_cpp`, xp)
}

ome_num_bootstrap_cpp <- function(xp) {
    .Call(`_apm_ome_num_bootstrap_cpp`, xp)
}

ome_point_means_cpp <- function(xp) {
    .Call(`_apm_ome_point_means_cpp`, xp)
}

ome_boot_means_cpp <- function(xp, b1) {
    .Call(`_apm_ome_boot_means_cpp`, xp, b1)
}

ome_C_cpp <- function(xp) {
    .Call(`_apm_ome_C_cpp`, xp)
}

ome_T_cpp <- function(xp) {
    .Call(`_apm_ome_T_cpp`, xp)
}

pc_estimator_new_cpp <- function(r, T_c, wb_xptr = NULL, q = 0L) {
    .Call(`_apm_pc_estimator_new_cpp`, r, T_c, wb_xptr, q)
}

pc_fe_estimator_new_cpp <- function(r, T_c, wb_xptr = NULL, q = 0L) {
    .Call(`_apm_pc_fe_estimator_new_cpp`, r, T_c, wb_xptr, q)
}

#' Check if aligned factors are identified across all cohorts
#'
#' This function uses the Observed Outcome Overlap (O^3) algorithm to determine
#' if there is sufficient overlap in observed outcomes across all cohorts to
#' uniquely identify all factor vectors expressed with respect to a common basis.
#' Identification is achieved if the O^3 algorithm terminates with a single
#' super cohort containing all of the original cohorts.
#'
#' @param observed_outcome_indices A list of integer vectors, where each
#'   vector contains the 1-based indices for the observed outcomes for a cohort.
#' @param r The model rank (number of factors). This determines the minimum
#'   overlap required for cohorts to be merged in the O^3 algorithm.
#' @return A logical value: \code{TRUE} if the factors are identified across
#'   all cohorts, \code{FALSE} otherwise.
#' @details
#' Two cohorts can have their factors aligned if they share at least \code{r}
#' observed outcomes. The O^3 algorithm iteratively merges cohorts that meet
#' this criterion. If all cohorts eventually merge into a single super cohort,
#' the factors are considered identified.
#'
#' @seealso \code{\link{o3_algorithm}} for the full O^3 algorithm output,
#'   \code{\link{summarize_identification}} for comprehensive identification metrics.
#' @examples
#' # Three cohorts with outcomes that can be aligned
#' ooi <- list(c(1L, 2L, 3L), c(2L, 3L, 4L), c(3L, 4L, 5L))
#' aligned_factors_identified(ooi, r = 2L)  # TRUE
#'
#' # Cohorts without sufficient overlap
#' ooi_no_id <- list(c(1L, 2L), c(3L, 4L))
#' aligned_factors_identified(ooi_no_id, r = 2L)  # FALSE
#' @export
aligned_factors_identified <- function(observed_outcome_indices, r) {
    .Call(`_apm_aligned_factors_identified`, observed_outcome_indices, r)
}

#' Get the largest super cohort from O^3 algorithm
#'
#' Returns the indices of cohorts belonging to the largest super cohort at a
#' specified iteration of the O^3 (Observed Outcome Overlap) algorithm. The
#' largest super cohort is determined by the total number of units across its
#' member cohorts.
#'
#' @param observed_outcome_indices A list of integer vectors (1-based) of
#'   observed outcomes per cohort.
#' @param cohort_sizes An integer vector of cohort sizes (number of units),
#'   with the same length as \code{observed_outcome_indices}.
#' @param max_model_rank Maximum model rank (r). This determines the minimum
#'   overlap required for cohorts to be merged.
#' @param iter Optional iteration selector. Defaults to \code{NULL} (final
#'   iteration). Positive values are 1-based (e.g., 1 = first iteration).
#'   Negative values count from the end (-1 = final, -2 = second-to-last).
#' @return An integer vector of 1-based cohort indices belonging to the
#'   largest super cohort at the selected iteration.
#' @details
#' This function is useful for identifying which cohorts can have their
#' factor estimates aligned when full identification is not achieved. The
#' cohorts in the largest super cohort share sufficient outcome overlap to
#' allow factor alignment among themselves.
#'
#' @seealso \code{\link{o3_algorithm}} for the full algorithm trace,
#'   \code{\link{aligned_factors_identified}} for checking full identification,
#'   \code{\link{summarize_identification}} for comprehensive metrics.
#' @examples
#' ooi <- list(c(1L, 2L, 3L), c(2L, 3L, 4L), c(5L, 6L))
#' sizes <- c(100L, 150L, 50L)
#' # Get cohorts in largest super cohort at final iteration
#' get_largest_super_cohort(ooi, sizes, max_model_rank = 2L)
#' @export
get_largest_super_cohort <- function(observed_outcome_indices, cohort_sizes, max_model_rank, iter = NULL) {
    .Call(`_apm_get_largest_super_cohort`, observed_outcome_indices, cohort_sizes, max_model_rank, iter)
}

#' Summarize factor identification for a panel (C++ backend)
#'
#' Computes summary statistics about factor identification based on the O^3
#' (Observed Outcome Overlap) algorithm. This is the C++ implementation called
#' by the R wrapper \code{\link{summarize_identification}}.
#'
#' @param observed_outcome_indices A list of integer vectors (1-based) of
#'   observed outcomes per cohort.
#' @param cohort_sizes An integer vector of cohort sizes (number of units),
#'   with the same length as \code{observed_outcome_indices}.
#' @param max_model_rank Maximum model rank (r). This determines the minimum
#'   overlap required for cohorts to be merged.
#' @param iter Optional iteration selector. Defaults to \code{NULL} (final
#'   iteration). Positive values are 1-based. Negative values count from end.
#' @param outcome_weights Optional numeric vector of outcome weights. If
#'   provided, used to compute weighted outcome coverage statistics.
#' @return A named list with identification summary fields:
#'   \describe{
#'     \item{largest_super_cohort_size}{Number of cohorts in the largest super cohort}
#'     \item{largest_super_cohort_share}{Share of total units in largest super cohort}
#'     \item{min_cohort_size_in_largest_super}{Minimum cohort size within largest super cohort}
#'     \item{num_outcomes_in_largest_super_cohort}{Number of unique outcomes in largest super cohort}
#'     \item{total_outcome_weight_in_largest_super_cohort}{Total weight of outcomes in largest super cohort}
#'     \item{share_outcomes_in_largest_super_cohort}{Share of outcomes in largest super cohort}
#'     \item{share_outcome_weight_in_largest_super_cohort}{Share of outcome weight in largest super cohort}
#'     \item{num_o3_iterations}{Number of O^3 algorithm iterations}
#'   }
#' @seealso \code{\link{summarize_identification}} for the R wrapper,
#'   \code{\link{o3_algorithm}} for the full algorithm trace.
#' @keywords internal
summarize_identification_cpp <- function(observed_outcome_indices, cohort_sizes, max_model_rank, iter = NULL, outcome_weights = NULL) {
    .Call(`_apm_summarize_identification_cpp`, observed_outcome_indices, cohort_sizes, max_model_rank, iter, outcome_weights)
}

#' Summarize factor identification for multiple panels (C++ backend)
#'
#' Computes identification summary statistics for multiple panels in a single
#' call. This is more efficient than calling \code{summarize_identification_cpp}
#' separately for each panel.
#'
#' @param observed_outcome_indices_list A list of lists, where each inner list
#'   contains integer vectors (1-based) of observed outcomes per cohort.
#' @param cohort_sizes_list A list of integer vectors of cohort sizes, one
#'   per panel. Each vector must match the length of the corresponding
#'   \code{observed_outcome_indices_list} element.
#' @param max_model_rank Maximum model rank (r). Applied to all panels.
#' @param iter Optional iteration selector. Defaults to \code{NULL} (final
#'   iteration). Applied to all panels.
#' @param outcome_weights_list Optional list of numeric vectors of outcome
#'   weights, one per panel. Defaults to equal weights for all panels.
#' @return A list of named lists, one per input panel, each with the same
#'   structure as \code{summarize_identification_cpp} output.
#' @seealso \code{\link{summarize_identification_cpp}} for single-panel version.
#' @keywords internal
summarize_identification_many_cpp <- function(observed_outcome_indices_list, cohort_sizes_list, max_model_rank, iter = NULL, outcome_weights_list = NULL) {
    .Call(`_apm_summarize_identification_many_cpp`, observed_outcome_indices_list, cohort_sizes_list, max_model_rank, iter, outcome_weights_list)
}

#' Count outcomes accessible via rank overlap for each cohort
#'
#' For each focal cohort, counts the (weighted) number of unique outcomes that
#' are observed in any cohort whose observed outcomes overlap with the focal
#' cohort in at least \code{rank} outcomes. The focal cohort's own outcomes
#' always contribute to its count. This measures how many outcomes each cohort
#' can potentially impute given the overlap structure.
#'
#' @param observed_outcome_indices A list of integer vectors (1-based) of
#'   observed outcomes per cohort.
#' @param rank Minimum number of overlapping observed outcomes required for
#'   another cohort to contribute its outcomes. Setting \code{rank = 0}
#'   includes all outcomes from all cohorts.
#' @param outcome_weights Optional numeric vector of outcome weights. If
#'   provided, must have length equal to the total number of outcomes.
#'   Defaults to equal weights (all ones).
#' @return A numeric vector of (weighted) counts, one per cohort. Each value
#'   represents the total weight of outcomes accessible to that cohort.
#' @details
#' This function helps assess how well each cohort can leverage information
#' from other cohorts for imputation. A cohort with a higher count has access
#' to more outcomes through sufficient overlap with other cohorts.
#'
#' When \code{rank} equals the model rank \code{r}, this indicates the number
#' of outcomes for which the cohort could potentially estimate factor loadings
#' and perform imputation.
#'
#' @seealso \code{\link{summarize_identification}} for comprehensive
#'   identification metrics, \code{\link{o3_algorithm}} for the overlap algorithm.
#' @examples
#' ooi <- list(c(1L, 2L, 3L), c(2L, 3L, 4L), c(5L, 6L))
#' # Count outcomes accessible with rank-2 overlap
#' count_outcomes_with_rank_overlap_per_cohort(ooi, rank = 2L)
#'
#' # With outcome weights
#' weights <- c(1, 2, 1, 1, 1, 1)  # outcome 2 weighted double
#' count_outcomes_with_rank_overlap_per_cohort(ooi, rank = 2L, outcome_weights = weights)
#' @export
count_outcomes_with_rank_overlap_per_cohort <- function(observed_outcome_indices, rank, outcome_weights = NULL) {
    .Call(`_apm_count_outcomes_with_rank_overlap_per_cohort`, observed_outcome_indices, rank, outcome_weights)
}

#' Mask observed outcome indices by cohort
#'
#' Applies a per-cohort outcome mask to a list of observed outcome indices,
#' removing specified outcomes from each cohort. This is useful for creating
#' hold-out sets for cross-validation or for simulating missing data patterns.
#'
#' @param observed_outcome_indices A list of integer vectors (1-based) of
#'   observed outcomes per cohort.
#' @param cohort_outcomes_to_mask_in Optional named list mapping 1-based cohort
#'   indices (as character names) to integer vectors of 1-based outcome indices
#'   to remove for that cohort. Names must be coercible to integers. If
#'   \code{NULL} or empty, the input is returned unchanged.
#' @return A list of integer vectors (1-based) with masked outcomes removed
#'   from each cohort's observed outcome set.
#' @details
#' This function is primarily used internally for computing error metrics
#' on held-out outcomes, but can also be useful for custom cross-validation
#' procedures.
#'
#' @examples
#' ooi <- list(c(1L, 2L, 3L), c(2L, 3L, 4L))
#' mask <- list(`1` = c(3L))  # Remove outcome 3 from cohort 1
#' get_masked_observed_outcome_indices(ooi, mask)
#' # Returns: list(c(1L, 2L), c(2L, 3L, 4L))
#' @keywords internal
get_masked_observed_outcome_indices <- function(observed_outcome_indices, cohort_outcomes_to_mask_in = NULL) {
    .Call(`_apm_get_masked_observed_outcome_indices`, observed_outcome_indices, cohort_outcomes_to_mask_in)
}

twfe_estimator_new_cpp <- function(T_c, wb_xptr = NULL, q = 0L) {
    .Call(`_apm_twfe_estimator_new_cpp`, T_c, wb_xptr, q)
}

