// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// aggregate_factor_model_params_cpp
SEXP aggregate_factor_model_params_cpp(Rcpp::List per_cohort_factor_estimates_xptrs, Rcpp::List observed_outcome_indices, SEXP cohort_weights_xptr);
RcppExport SEXP _apm_aggregate_factor_model_params_cpp(SEXP per_cohort_factor_estimates_xptrsSEXP, SEXP observed_outcome_indicesSEXP, SEXP cohort_weights_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type per_cohort_factor_estimates_xptrs(per_cohort_factor_estimates_xptrsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices(observed_outcome_indicesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type cohort_weights_xptr(cohort_weights_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(aggregate_factor_model_params_cpp(per_cohort_factor_estimates_xptrs, observed_outcome_indices, cohort_weights_xptr));
    return rcpp_result_gen;
END_RCPP
}
// aggregate_factor_model_params_by_spec_cpp
Rcpp::List aggregate_factor_model_params_by_spec_cpp(Rcpp::List cohort_specific_factor_ests, Rcpp::List observed_outcome_indices, Rcpp::List cohort_weights_by_spec);
RcppExport SEXP _apm_aggregate_factor_model_params_by_spec_cpp(SEXP cohort_specific_factor_estsSEXP, SEXP observed_outcome_indicesSEXP, SEXP cohort_weights_by_specSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type cohort_specific_factor_ests(cohort_specific_factor_estsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices(observed_outcome_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cohort_weights_by_spec(cohort_weights_by_specSEXP);
    rcpp_result_gen = Rcpp::wrap(aggregate_factor_model_params_by_spec_cpp(cohort_specific_factor_ests, observed_outcome_indices, cohort_weights_by_spec));
    return rcpp_result_gen;
END_RCPP
}
// get_version
std::string get_version();
RcppExport SEXP _apm_get_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_version());
    return rcpp_result_gen;
END_RCPP
}
// align_factors_using_apm
arma::mat align_factors_using_apm(Rcpp::List cohort_factor_matrices, Rcpp::List observed_outcome_indices, Rcpp::Nullable<Rcpp::NumericVector> cohort_weights);
RcppExport SEXP _apm_align_factors_using_apm(SEXP cohort_factor_matricesSEXP, SEXP observed_outcome_indicesSEXP, SEXP cohort_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type cohort_factor_matrices(cohort_factor_matricesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices(observed_outcome_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type cohort_weights(cohort_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(align_factors_using_apm(cohort_factor_matrices, observed_outcome_indices, cohort_weights));
    return rcpp_result_gen;
END_RCPP
}
// compute_aggregated_projection_matrix
arma::mat compute_aggregated_projection_matrix(Rcpp::List cohort_factor_matrices, Rcpp::List observed_outcome_indices, Rcpp::Nullable<Rcpp::NumericVector> cohort_weights);
RcppExport SEXP _apm_compute_aggregated_projection_matrix(SEXP cohort_factor_matricesSEXP, SEXP observed_outcome_indicesSEXP, SEXP cohort_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type cohort_factor_matrices(cohort_factor_matricesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices(observed_outcome_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type cohort_weights(cohort_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_aggregated_projection_matrix(cohort_factor_matrices, observed_outcome_indices, cohort_weights));
    return rcpp_result_gen;
END_RCPP
}
// aggregate_cohort_specific_covariate_coefs
arma::vec aggregate_cohort_specific_covariate_coefs(Rcpp::List a_c_vec);
RcppExport SEXP _apm_aggregate_cohort_specific_covariate_coefs(SEXP a_c_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type a_c_vec(a_c_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(aggregate_cohort_specific_covariate_coefs(a_c_vec));
    return rcpp_result_gen;
END_RCPP
}
// aggregate_cohort_specific_outcome_fes
arma::vec aggregate_cohort_specific_outcome_fes(Rcpp::List g_0_c_vec, Rcpp::List observed_outcome_indices);
RcppExport SEXP _apm_aggregate_cohort_specific_outcome_fes(SEXP g_0_c_vecSEXP, SEXP observed_outcome_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type g_0_c_vec(g_0_c_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices(observed_outcome_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(aggregate_cohort_specific_outcome_fes(g_0_c_vec, observed_outcome_indices));
    return rcpp_result_gen;
END_RCPP
}
// impute_outcomes_from_obs_outcomes
arma::vec impute_outcomes_from_obs_outcomes(const arma::mat& G, const arma::uvec& T_c, const arma::vec& m_c, Rcpp::Nullable<Rcpp::NumericVector> g_0, Rcpp::Nullable<Rcpp::NumericVector> a, Rcpp::Nullable<Rcpp::NumericMatrix> X_c);
RcppExport SEXP _apm_impute_outcomes_from_obs_outcomes(SEXP GSEXP, SEXP T_cSEXP, SEXP m_cSEXP, SEXP g_0SEXP, SEXP aSEXP, SEXP X_cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type T_c(T_cSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m_c(m_cSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type g_0(g_0SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type X_c(X_cSEXP);
    rcpp_result_gen = Rcpp::wrap(impute_outcomes_from_obs_outcomes(G, T_c, m_c, g_0, a, X_c));
    return rcpp_result_gen;
END_RCPP
}
// impute_outcomes_across_cohorts_from_obs_outcomes
arma::mat impute_outcomes_across_cohorts_from_obs_outcomes(const arma::mat& G, Rcpp::List observed_outcome_indices, Rcpp::List m_c_vec, Rcpp::Nullable<Rcpp::NumericVector> g_0, Rcpp::Nullable<Rcpp::NumericVector> a, Rcpp::Nullable<Rcpp::List> X_c_vec);
RcppExport SEXP _apm_impute_outcomes_across_cohorts_from_obs_outcomes(SEXP GSEXP, SEXP observed_outcome_indicesSEXP, SEXP m_c_vecSEXP, SEXP g_0SEXP, SEXP aSEXP, SEXP X_c_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices(observed_outcome_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type m_c_vec(m_c_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type g_0(g_0SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type X_c_vec(X_c_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(impute_outcomes_across_cohorts_from_obs_outcomes(G, observed_outcome_indices, m_c_vec, g_0, a, X_c_vec));
    return rcpp_result_gen;
END_RCPP
}
// o3_algorithm
Rcpp::List o3_algorithm(Rcpp::List observed_outcome_indices, unsigned int r);
RcppExport SEXP _apm_o3_algorithm(SEXP observed_outcome_indicesSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices(observed_outcome_indicesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(o3_algorithm(observed_outcome_indices, r));
    return rcpp_result_gen;
END_RCPP
}
// impute_outcomes_across_cohorts
arma::mat impute_outcomes_across_cohorts(const arma::mat& G, const arma::mat& L, Rcpp::Nullable<Rcpp::NumericVector> g_0, Rcpp::Nullable<Rcpp::NumericVector> a, Rcpp::Nullable<Rcpp::List> X_c);
RcppExport SEXP _apm_impute_outcomes_across_cohorts(SEXP GSEXP, SEXP LSEXP, SEXP g_0SEXP, SEXP aSEXP, SEXP X_cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type g_0(g_0SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type X_c(X_cSEXP);
    rcpp_result_gen = Rcpp::wrap(impute_outcomes_across_cohorts(G, L, g_0, a, X_c));
    return rcpp_result_gen;
END_RCPP
}
// get_weighted_bootstrap_ptr_cpp
SEXP get_weighted_bootstrap_ptr_cpp(std::size_t N, std::size_t B, const std::string& type, Rcpp::Nullable<Rcpp::NumericVector> seed);
RcppExport SEXP _apm_get_weighted_bootstrap_ptr_cpp(SEXP NSEXP, SEXP BSEXP, SEXP typeSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::size_t >::type N(NSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type B(BSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(get_weighted_bootstrap_ptr_cpp(N, B, type, seed));
    return rcpp_result_gen;
END_RCPP
}
// wb_n_obs_cpp
std::size_t wb_n_obs_cpp(SEXP xp);
RcppExport SEXP _apm_wb_n_obs_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(wb_n_obs_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// wb_n_bootstraps_cpp
std::size_t wb_n_bootstraps_cpp(SEXP xp);
RcppExport SEXP _apm_wb_n_bootstraps_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(wb_n_bootstraps_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// wb_draw_cpp
arma::vec wb_draw_cpp(SEXP xp, std::size_t b);
RcppExport SEXP _apm_wb_draw_cpp(SEXP xpSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(wb_draw_cpp(xp, b));
    return rcpp_result_gen;
END_RCPP
}
// wb_obs_cpp
arma::vec wb_obs_cpp(SEXP xp, std::size_t i);
RcppExport SEXP _apm_wb_obs_cpp(SEXP xpSEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type i(iSEXP);
    rcpp_result_gen = Rcpp::wrap(wb_obs_cpp(xp, i));
    return rcpp_result_gen;
END_RCPP
}
// wb_obs_rows_cpp
arma::mat wb_obs_rows_cpp(SEXP xp, const arma::uvec& idx);
RcppExport SEXP _apm_wb_obs_rows_cpp(SEXP xpSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(wb_obs_rows_cpp(xp, idx));
    return rcpp_result_gen;
END_RCPP
}
// wb_weights_cpp
arma::mat wb_weights_cpp(SEXP xp);
RcppExport SEXP _apm_wb_weights_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(wb_weights_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// get_bootstrap_inference_cpp
SEXP get_bootstrap_inference_cpp(Rcpp::NumericVector point_ests, Rcpp::NumericMatrix bootstrap_replicates, std::size_t N, double sig_level);
RcppExport SEXP _apm_get_bootstrap_inference_cpp(SEXP point_estsSEXP, SEXP bootstrap_replicatesSEXP, SEXP NSEXP, SEXP sig_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type point_ests(point_estsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type bootstrap_replicates(bootstrap_replicatesSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type sig_level(sig_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(get_bootstrap_inference_cpp(point_ests, bootstrap_replicates, N, sig_level));
    return rcpp_result_gen;
END_RCPP
}
// sir_point_cpp
Rcpp::NumericVector sir_point_cpp(SEXP xp);
RcppExport SEXP _apm_sir_point_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(sir_point_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// sir_pointwise_t_cpp
Rcpp::NumericVector sir_pointwise_t_cpp(SEXP xp);
RcppExport SEXP _apm_sir_pointwise_t_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(sir_pointwise_t_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// sir_pointwise_p_cpp
Rcpp::NumericVector sir_pointwise_p_cpp(SEXP xp);
RcppExport SEXP _apm_sir_pointwise_p_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(sir_pointwise_p_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// sir_std_error_cpp
Rcpp::NumericVector sir_std_error_cpp(SEXP xp);
RcppExport SEXP _apm_sir_std_error_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(sir_std_error_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// sir_sig_level_cpp
double sir_sig_level_cpp(SEXP xp);
RcppExport SEXP _apm_sir_sig_level_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(sir_sig_level_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// sir_ci_lb_cpp
Rcpp::NumericVector sir_ci_lb_cpp(SEXP xp);
RcppExport SEXP _apm_sir_ci_lb_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(sir_ci_lb_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// sir_ci_ub_cpp
Rcpp::NumericVector sir_ci_ub_cpp(SEXP xp);
RcppExport SEXP _apm_sir_ci_ub_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(sir_ci_ub_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// sir_fwer_control_p_cpp
Rcpp::NumericVector sir_fwer_control_p_cpp(SEXP xp);
RcppExport SEXP _apm_sir_fwer_control_p_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(sir_fwer_control_p_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// sir_cb_lb_cpp
Rcpp::NumericVector sir_cb_lb_cpp(SEXP xp);
RcppExport SEXP _apm_sir_cb_lb_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(sir_cb_lb_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// sir_cb_ub_cpp
Rcpp::NumericVector sir_cb_ub_cpp(SEXP xp);
RcppExport SEXP _apm_sir_cb_ub_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(sir_cb_ub_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// cwe_has_bootstrap_cpp
bool cwe_has_bootstrap_cpp(SEXP xp);
RcppExport SEXP _apm_cwe_has_bootstrap_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(cwe_has_bootstrap_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// cwe_num_bootstrap_cpp
std::size_t cwe_num_bootstrap_cpp(SEXP xp);
RcppExport SEXP _apm_cwe_num_bootstrap_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(cwe_num_bootstrap_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// cwe_point_weights_cpp
arma::vec cwe_point_weights_cpp(SEXP xp);
RcppExport SEXP _apm_cwe_point_weights_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(cwe_point_weights_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// cwe_boot_weights_cpp
arma::vec cwe_boot_weights_cpp(SEXP xp, std::size_t b);
RcppExport SEXP _apm_cwe_boot_weights_cpp(SEXP xpSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(cwe_boot_weights_cpp(xp, b));
    return rcpp_result_gen;
END_RCPP
}
// build_R_panel_holder_cpp
SEXP build_R_panel_holder_cpp(Rcpp::DataFrame processed_panel, Rcpp::List observed_outcome_indices, const std::string& outcome_value_col, Rcpp::CharacterVector covar_cols, Rcpp::CharacterVector auxiliary_cols, Rcpp::Nullable<Rcpp::IntegerVector> num_units_in);
RcppExport SEXP _apm_build_R_panel_holder_cpp(SEXP processed_panelSEXP, SEXP observed_outcome_indicesSEXP, SEXP outcome_value_colSEXP, SEXP covar_colsSEXP, SEXP auxiliary_colsSEXP, SEXP num_units_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type processed_panel(processed_panelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices(observed_outcome_indicesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type outcome_value_col(outcome_value_colSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type covar_cols(covar_colsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type auxiliary_cols(auxiliary_colsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type num_units_in(num_units_inSEXP);
    rcpp_result_gen = Rcpp::wrap(build_R_panel_holder_cpp(processed_panel, observed_outcome_indices, outcome_value_col, covar_cols, auxiliary_cols, num_units_in));
    return rcpp_result_gen;
END_RCPP
}
// est_cohort_specific_params_from_panel_cpp
Rcpp::List est_cohort_specific_params_from_panel_cpp(SEXP panel_holder_xptr, Rcpp::List est_specs, SEXP bootstrap_xptr, Rcpp::Nullable<Rcpp::IntegerVector> num_threads_in, Rcpp::Nullable<Rcpp::List> cohort_outcomes_to_mask_in);
RcppExport SEXP _apm_est_cohort_specific_params_from_panel_cpp(SEXP panel_holder_xptrSEXP, SEXP est_specsSEXP, SEXP bootstrap_xptrSEXP, SEXP num_threads_inSEXP, SEXP cohort_outcomes_to_mask_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type panel_holder_xptr(panel_holder_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type est_specs(est_specsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type bootstrap_xptr(bootstrap_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type num_threads_in(num_threads_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type cohort_outcomes_to_mask_in(cohort_outcomes_to_mask_inSEXP);
    rcpp_result_gen = Rcpp::wrap(est_cohort_specific_params_from_panel_cpp(panel_holder_xptr, est_specs, bootstrap_xptr, num_threads_in, cohort_outcomes_to_mask_in));
    return rcpp_result_gen;
END_RCPP
}
// est_masked_outcome_mean_err_metrics_cpp
Rcpp::DataFrame est_masked_outcome_mean_err_metrics_cpp(Rcpp::List comps_list);
RcppExport SEXP _apm_est_masked_outcome_mean_err_metrics_cpp(SEXP comps_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type comps_list(comps_listSEXP);
    rcpp_result_gen = Rcpp::wrap(est_masked_outcome_mean_err_metrics_cpp(comps_list));
    return rcpp_result_gen;
END_RCPP
}
// estimate_outcome_means_across_cohorts_cpp
SEXP estimate_outcome_means_across_cohorts_cpp(SEXP factor_model_estimates_xptr, Rcpp::List observed_outcome_indices, Rcpp::List suff_stat_estimates_xptrs);
RcppExport SEXP _apm_estimate_outcome_means_across_cohorts_cpp(SEXP factor_model_estimates_xptrSEXP, SEXP observed_outcome_indicesSEXP, SEXP suff_stat_estimates_xptrsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type factor_model_estimates_xptr(factor_model_estimates_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices(observed_outcome_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type suff_stat_estimates_xptrs(suff_stat_estimates_xptrsSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_outcome_means_across_cohorts_cpp(factor_model_estimates_xptr, observed_outcome_indices, suff_stat_estimates_xptrs));
    return rcpp_result_gen;
END_RCPP
}
// estimate_outcome_means_across_cohorts_by_spec_cpp
Rcpp::List estimate_outcome_means_across_cohorts_by_spec_cpp(Rcpp::List factor_model_estimates_by_spec, Rcpp::List observed_outcome_indices, Rcpp::List suff_stat_estimates_xptrs);
RcppExport SEXP _apm_estimate_outcome_means_across_cohorts_by_spec_cpp(SEXP factor_model_estimates_by_specSEXP, SEXP observed_outcome_indicesSEXP, SEXP suff_stat_estimates_xptrsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_model_estimates_by_spec(factor_model_estimates_by_specSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices(observed_outcome_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type suff_stat_estimates_xptrs(suff_stat_estimates_xptrsSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_outcome_means_across_cohorts_by_spec_cpp(factor_model_estimates_by_spec, observed_outcome_indices, suff_stat_estimates_xptrs));
    return rcpp_result_gen;
END_RCPP
}
// get_cpp_default_concurrency
int get_cpp_default_concurrency();
RcppExport SEXP _apm_get_cpp_default_concurrency() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_cpp_default_concurrency());
    return rcpp_result_gen;
END_RCPP
}
// make_factor_model_estimates_cpp
SEXP make_factor_model_estimates_cpp(const arma::mat& G, Rcpp::Nullable<arma::vec> g0, Rcpp::Nullable<arma::vec> a, int B);
RcppExport SEXP _apm_make_factor_model_estimates_cpp(SEXP GSEXP, SEXP g0SEXP, SEXP aSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::vec> >::type g0(g0SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::vec> >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(make_factor_model_estimates_cpp(G, g0, a, B));
    return rcpp_result_gen;
END_RCPP
}
// make_outcome_mean_suff_stat_estimates_cpp
SEXP make_outcome_mean_suff_stat_estimates_cpp(const arma::vec& observed_means, Rcpp::Nullable<arma::mat> covar_means, int B);
RcppExport SEXP _apm_make_outcome_mean_suff_stat_estimates_cpp(SEXP observed_meansSEXP, SEXP covar_meansSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type observed_means(observed_meansSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type covar_means(covar_meansSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(make_outcome_mean_suff_stat_estimates_cpp(observed_means, covar_means, B));
    return rcpp_result_gen;
END_RCPP
}
// make_cohort_weight_estimates_cpp
SEXP make_cohort_weight_estimates_cpp(const arma::vec& cohort_weights, Rcpp::Nullable<Rcpp::List> bootstrap_weights);
RcppExport SEXP _apm_make_cohort_weight_estimates_cpp(SEXP cohort_weightsSEXP, SEXP bootstrap_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type cohort_weights(cohort_weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type bootstrap_weights(bootstrap_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(make_cohort_weight_estimates_cpp(cohort_weights, bootstrap_weights));
    return rcpp_result_gen;
END_RCPP
}
// est_target_params_cpp
SEXP est_target_params_cpp(SEXP ome_xptr, Rcpp::Nullable<Rcpp::List> stats_xptrs_by_cohort, Rcpp::Nullable<Rcpp::List> eta_xptrs_by_cohort, Rcpp::Function r_fn);
RcppExport SEXP _apm_est_target_params_cpp(SEXP ome_xptrSEXP, SEXP stats_xptrs_by_cohortSEXP, SEXP eta_xptrs_by_cohortSEXP, SEXP r_fnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ome_xptr(ome_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type stats_xptrs_by_cohort(stats_xptrs_by_cohortSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type eta_xptrs_by_cohort(eta_xptrs_by_cohortSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type r_fn(r_fnSEXP);
    rcpp_result_gen = Rcpp::wrap(est_target_params_cpp(ome_xptr, stats_xptrs_by_cohort, eta_xptrs_by_cohort, r_fn));
    return rcpp_result_gen;
END_RCPP
}
// tpe_has_bootstrap_cpp
bool tpe_has_bootstrap_cpp(SEXP xp_);
RcppExport SEXP _apm_tpe_has_bootstrap_cpp(SEXP xp_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp_(xp_SEXP);
    rcpp_result_gen = Rcpp::wrap(tpe_has_bootstrap_cpp(xp_));
    return rcpp_result_gen;
END_RCPP
}
// tpe_num_bootstrap_cpp
int tpe_num_bootstrap_cpp(SEXP xp_);
RcppExport SEXP _apm_tpe_num_bootstrap_cpp(SEXP xp_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp_(xp_SEXP);
    rcpp_result_gen = Rcpp::wrap(tpe_num_bootstrap_cpp(xp_));
    return rcpp_result_gen;
END_RCPP
}
// tpe_p_cpp
int tpe_p_cpp(SEXP xp_);
RcppExport SEXP _apm_tpe_p_cpp(SEXP xp_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp_(xp_SEXP);
    rcpp_result_gen = Rcpp::wrap(tpe_p_cpp(xp_));
    return rcpp_result_gen;
END_RCPP
}
// tpe_point_params_cpp
Rcpp::NumericVector tpe_point_params_cpp(SEXP xp_);
RcppExport SEXP _apm_tpe_point_params_cpp(SEXP xp_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp_(xp_SEXP);
    rcpp_result_gen = Rcpp::wrap(tpe_point_params_cpp(xp_));
    return rcpp_result_gen;
END_RCPP
}
// tpe_boot_params_cpp
Rcpp::NumericVector tpe_boot_params_cpp(SEXP xp_, int b1);
RcppExport SEXP _apm_tpe_boot_params_cpp(SEXP xp_SEXP, SEXP b1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp_(xp_SEXP);
    Rcpp::traits::input_parameter< int >::type b1(b1SEXP);
    rcpp_result_gen = Rcpp::wrap(tpe_boot_params_cpp(xp_, b1));
    return rcpp_result_gen;
END_RCPP
}
// tpe_boot_params_matrix_cpp
Rcpp::NumericMatrix tpe_boot_params_matrix_cpp(SEXP xp_);
RcppExport SEXP _apm_tpe_boot_params_matrix_cpp(SEXP xp_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp_(xp_SEXP);
    rcpp_result_gen = Rcpp::wrap(tpe_boot_params_matrix_cpp(xp_));
    return rcpp_result_gen;
END_RCPP
}
// est_target_params_by_spec_cpp
Rcpp::List est_target_params_by_spec_cpp(Rcpp::List ome_by_spec, Rcpp::Nullable<Rcpp::List> stats_xptrs_by_cohort, Rcpp::Nullable<Rcpp::List> eta_xptrs_by_cohort, Rcpp::Function r_fn);
RcppExport SEXP _apm_est_target_params_by_spec_cpp(SEXP ome_by_specSEXP, SEXP stats_xptrs_by_cohortSEXP, SEXP eta_xptrs_by_cohortSEXP, SEXP r_fnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type ome_by_spec(ome_by_specSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type stats_xptrs_by_cohort(stats_xptrs_by_cohortSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type eta_xptrs_by_cohort(eta_xptrs_by_cohortSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type r_fn(r_fnSEXP);
    rcpp_result_gen = Rcpp::wrap(est_target_params_by_spec_cpp(ome_by_spec, stats_xptrs_by_cohort, eta_xptrs_by_cohort, r_fn));
    return rcpp_result_gen;
END_RCPP
}
// get_target_param_diff_ests_cpp
SEXP get_target_param_diff_ests_cpp(SEXP tpe1_xp, SEXP tpe2_xp);
RcppExport SEXP _apm_get_target_param_diff_ests_cpp(SEXP tpe1_xpSEXP, SEXP tpe2_xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tpe1_xp(tpe1_xpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tpe2_xp(tpe2_xpSEXP);
    rcpp_result_gen = Rcpp::wrap(get_target_param_diff_ests_cpp(tpe1_xp, tpe2_xp));
    return rcpp_result_gen;
END_RCPP
}
// combine_target_param_ests_cpp
SEXP combine_target_param_ests_cpp(SEXP tpe1_xp, SEXP tpe2_xp);
RcppExport SEXP _apm_combine_target_param_ests_cpp(SEXP tpe1_xpSEXP, SEXP tpe2_xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tpe1_xp(tpe1_xpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tpe2_xp(tpe2_xpSEXP);
    rcpp_result_gen = Rcpp::wrap(combine_target_param_ests_cpp(tpe1_xp, tpe2_xp));
    return rcpp_result_gen;
END_RCPP
}
// combine_target_param_ests_multi_cpp
SEXP combine_target_param_ests_multi_cpp(Rcpp::List tpe_list);
RcppExport SEXP _apm_combine_target_param_ests_multi_cpp(SEXP tpe_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type tpe_list(tpe_listSEXP);
    rcpp_result_gen = Rcpp::wrap(combine_target_param_ests_multi_cpp(tpe_list));
    return rcpp_result_gen;
END_RCPP
}
// subset_target_param_ests_cpp
SEXP subset_target_param_ests_cpp(SEXP tpe_xp, Rcpp::IntegerVector indices_0based);
RcppExport SEXP _apm_subset_target_param_ests_cpp(SEXP tpe_xpSEXP, SEXP indices_0basedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tpe_xp(tpe_xpSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type indices_0based(indices_0basedSEXP);
    rcpp_result_gen = Rcpp::wrap(subset_target_param_ests_cpp(tpe_xp, indices_0based));
    return rcpp_result_gen;
END_RCPP
}
// est_target_param_components_from_panel_cpp
Rcpp::List est_target_param_components_from_panel_cpp(SEXP panel_holder_xptr, Rcpp::List est_specs, SEXP bootstrap_xptr, Rcpp::Nullable<Rcpp::IntegerVector> num_threads_in, Rcpp::Nullable<Rcpp::List> cohort_outcomes_to_mask_in, bool est_outcome_means_via_imputation, Rcpp::Nullable<Rcpp::List> imputation_options_in);
RcppExport SEXP _apm_est_target_param_components_from_panel_cpp(SEXP panel_holder_xptrSEXP, SEXP est_specsSEXP, SEXP bootstrap_xptrSEXP, SEXP num_threads_inSEXP, SEXP cohort_outcomes_to_mask_inSEXP, SEXP est_outcome_means_via_imputationSEXP, SEXP imputation_options_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type panel_holder_xptr(panel_holder_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type est_specs(est_specsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type bootstrap_xptr(bootstrap_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type num_threads_in(num_threads_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type cohort_outcomes_to_mask_in(cohort_outcomes_to_mask_inSEXP);
    Rcpp::traits::input_parameter< bool >::type est_outcome_means_via_imputation(est_outcome_means_via_imputationSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type imputation_options_in(imputation_options_inSEXP);
    rcpp_result_gen = Rcpp::wrap(est_target_param_components_from_panel_cpp(panel_holder_xptr, est_specs, bootstrap_xptr, num_threads_in, cohort_outcomes_to_mask_in, est_outcome_means_via_imputation, imputation_options_in));
    return rcpp_result_gen;
END_RCPP
}
// target_param_inference_cpp
SEXP target_param_inference_cpp(SEXP tpe_xptr, SEXP panel_holder_xptr, double sig_level);
RcppExport SEXP _apm_target_param_inference_cpp(SEXP tpe_xptrSEXP, SEXP panel_holder_xptrSEXP, SEXP sig_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tpe_xptr(tpe_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type panel_holder_xptr(panel_holder_xptrSEXP);
    Rcpp::traits::input_parameter< double >::type sig_level(sig_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(target_param_inference_cpp(tpe_xptr, panel_holder_xptr, sig_level));
    return rcpp_result_gen;
END_RCPP
}
// target_param_inference_by_spec_cpp
Rcpp::List target_param_inference_by_spec_cpp(Rcpp::List tpe_by_spec, SEXP panel_holder_xptr, double sig_level);
RcppExport SEXP _apm_target_param_inference_by_spec_cpp(SEXP tpe_by_specSEXP, SEXP panel_holder_xptrSEXP, SEXP sig_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type tpe_by_spec(tpe_by_specSEXP);
    Rcpp::traits::input_parameter< SEXP >::type panel_holder_xptr(panel_holder_xptrSEXP);
    Rcpp::traits::input_parameter< double >::type sig_level(sig_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(target_param_inference_by_spec_cpp(tpe_by_spec, panel_holder_xptr, sig_level));
    return rcpp_result_gen;
END_RCPP
}
// estimator_add_data_cpp
void estimator_add_data_cpp(SEXP xp, arma::uvec unit_idxs_1based, const arma::mat& Y, Rcpp::Nullable<arma::cube> X);
RcppExport SEXP _apm_estimator_add_data_cpp(SEXP xpSEXP, SEXP unit_idxs_1basedSEXP, SEXP YSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type unit_idxs_1based(unit_idxs_1basedSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::cube> >::type X(XSEXP);
    estimator_add_data_cpp(xp, unit_idxs_1based, Y, X);
    return R_NilValue;
END_RCPP
}
// estimator_add_datum_cpp
void estimator_add_datum_cpp(SEXP xp, std::size_t unit_idx_1based, const arma::vec& Y, Rcpp::Nullable<arma::mat> X);
RcppExport SEXP _apm_estimator_add_datum_cpp(SEXP xpSEXP, SEXP unit_idx_1basedSEXP, SEXP YSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type unit_idx_1based(unit_idx_1basedSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type X(XSEXP);
    estimator_add_datum_cpp(xp, unit_idx_1based, Y, X);
    return R_NilValue;
END_RCPP
}
// estimator_r_cpp
std::size_t estimator_r_cpp(SEXP xp);
RcppExport SEXP _apm_estimator_r_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(estimator_r_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// estimator_Tc_cpp
std::size_t estimator_Tc_cpp(SEXP xp);
RcppExport SEXP _apm_estimator_Tc_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(estimator_Tc_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// estimator_q_cpp
std::size_t estimator_q_cpp(SEXP xp);
RcppExport SEXP _apm_estimator_q_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(estimator_q_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// estimator_B_cpp
std::size_t estimator_B_cpp(SEXP xp);
RcppExport SEXP _apm_estimator_B_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(estimator_B_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// estimator_estimate_cpp
SEXP estimator_estimate_cpp(SEXP xp);
RcppExport SEXP _apm_estimator_estimate_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(estimator_estimate_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// fme_has_bootstrap_cpp
bool fme_has_bootstrap_cpp(SEXP fme);
RcppExport SEXP _apm_fme_has_bootstrap_cpp(SEXP fmeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fme(fmeSEXP);
    rcpp_result_gen = Rcpp::wrap(fme_has_bootstrap_cpp(fme));
    return rcpp_result_gen;
END_RCPP
}
// fme_num_bootstrap_cpp
std::size_t fme_num_bootstrap_cpp(SEXP fme);
RcppExport SEXP _apm_fme_num_bootstrap_cpp(SEXP fmeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fme(fmeSEXP);
    rcpp_result_gen = Rcpp::wrap(fme_num_bootstrap_cpp(fme));
    return rcpp_result_gen;
END_RCPP
}
// fme_has_g0_cpp
bool fme_has_g0_cpp(SEXP fme);
RcppExport SEXP _apm_fme_has_g0_cpp(SEXP fmeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fme(fmeSEXP);
    rcpp_result_gen = Rcpp::wrap(fme_has_g0_cpp(fme));
    return rcpp_result_gen;
END_RCPP
}
// fme_has_a_cpp
bool fme_has_a_cpp(SEXP fme);
RcppExport SEXP _apm_fme_has_a_cpp(SEXP fmeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fme(fmeSEXP);
    rcpp_result_gen = Rcpp::wrap(fme_has_a_cpp(fme));
    return rcpp_result_gen;
END_RCPP
}
// fme_point_G_cpp
arma::mat fme_point_G_cpp(SEXP fme);
RcppExport SEXP _apm_fme_point_G_cpp(SEXP fmeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fme(fmeSEXP);
    rcpp_result_gen = Rcpp::wrap(fme_point_G_cpp(fme));
    return rcpp_result_gen;
END_RCPP
}
// fme_point_g0_cpp
arma::vec fme_point_g0_cpp(SEXP fme);
RcppExport SEXP _apm_fme_point_g0_cpp(SEXP fmeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fme(fmeSEXP);
    rcpp_result_gen = Rcpp::wrap(fme_point_g0_cpp(fme));
    return rcpp_result_gen;
END_RCPP
}
// fme_point_a_cpp
arma::vec fme_point_a_cpp(SEXP fme);
RcppExport SEXP _apm_fme_point_a_cpp(SEXP fmeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fme(fmeSEXP);
    rcpp_result_gen = Rcpp::wrap(fme_point_a_cpp(fme));
    return rcpp_result_gen;
END_RCPP
}
// fme_boot_G_cpp
arma::mat fme_boot_G_cpp(SEXP fme, std::size_t b);
RcppExport SEXP _apm_fme_boot_G_cpp(SEXP fmeSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fme(fmeSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fme_boot_G_cpp(fme, b));
    return rcpp_result_gen;
END_RCPP
}
// fme_boot_g0_cpp
arma::vec fme_boot_g0_cpp(SEXP fme, std::size_t b);
RcppExport SEXP _apm_fme_boot_g0_cpp(SEXP fmeSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fme(fmeSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fme_boot_g0_cpp(fme, b));
    return rcpp_result_gen;
END_RCPP
}
// fme_boot_a_cpp
arma::vec fme_boot_a_cpp(SEXP fme, std::size_t b);
RcppExport SEXP _apm_fme_boot_a_cpp(SEXP fmeSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fme(fmeSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fme_boot_a_cpp(fme, b));
    return rcpp_result_gen;
END_RCPP
}
// fme_point_L_cpp
arma::mat fme_point_L_cpp(SEXP fme);
RcppExport SEXP _apm_fme_point_L_cpp(SEXP fmeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fme(fmeSEXP);
    rcpp_result_gen = Rcpp::wrap(fme_point_L_cpp(fme));
    return rcpp_result_gen;
END_RCPP
}
// fme_boot_L_cpp
arma::mat fme_boot_L_cpp(SEXP fme, std::size_t b);
RcppExport SEXP _apm_fme_boot_L_cpp(SEXP fmeSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fme(fmeSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fme_boot_L_cpp(fme, b));
    return rcpp_result_gen;
END_RCPP
}
// est_fgw_bipartite_match_outcome_diff_params_multi_cpp
SEXP est_fgw_bipartite_match_outcome_diff_params_multi_cpp(SEXP ome_xptr, Rcpp::Nullable<Rcpp::List> stats_xptrs_by_cohort, Rcpp::IntegerVector outcome_indices_1, Rcpp::IntegerVector outcome_indices_2, Rcpp::List observed_outcome_indices_list, Rcpp::Nullable<Rcpp::NumericVector> outcome_weights, bool use_observed_outcome_means);
RcppExport SEXP _apm_est_fgw_bipartite_match_outcome_diff_params_multi_cpp(SEXP ome_xptrSEXP, SEXP stats_xptrs_by_cohortSEXP, SEXP outcome_indices_1SEXP, SEXP outcome_indices_2SEXP, SEXP observed_outcome_indices_listSEXP, SEXP outcome_weightsSEXP, SEXP use_observed_outcome_meansSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ome_xptr(ome_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type stats_xptrs_by_cohort(stats_xptrs_by_cohortSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type outcome_indices_1(outcome_indices_1SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type outcome_indices_2(outcome_indices_2SEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices_list(observed_outcome_indices_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type outcome_weights(outcome_weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_observed_outcome_means(use_observed_outcome_meansSEXP);
    rcpp_result_gen = Rcpp::wrap(est_fgw_bipartite_match_outcome_diff_params_multi_cpp(ome_xptr, stats_xptrs_by_cohort, outcome_indices_1, outcome_indices_2, observed_outcome_indices_list, outcome_weights, use_observed_outcome_means));
    return rcpp_result_gen;
END_RCPP
}
// est_fgw_bipartite_match_outcome_diff_params_cpp
SEXP est_fgw_bipartite_match_outcome_diff_params_cpp(SEXP ome_xptr, Rcpp::Nullable<Rcpp::List> stats_xptrs_by_cohort, int outcome_idx_1, int outcome_idx_2, Rcpp::List observed_outcome_indices_list, bool use_observed_outcome_means);
RcppExport SEXP _apm_est_fgw_bipartite_match_outcome_diff_params_cpp(SEXP ome_xptrSEXP, SEXP stats_xptrs_by_cohortSEXP, SEXP outcome_idx_1SEXP, SEXP outcome_idx_2SEXP, SEXP observed_outcome_indices_listSEXP, SEXP use_observed_outcome_meansSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ome_xptr(ome_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type stats_xptrs_by_cohort(stats_xptrs_by_cohortSEXP);
    Rcpp::traits::input_parameter< int >::type outcome_idx_1(outcome_idx_1SEXP);
    Rcpp::traits::input_parameter< int >::type outcome_idx_2(outcome_idx_2SEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices_list(observed_outcome_indices_listSEXP);
    Rcpp::traits::input_parameter< bool >::type use_observed_outcome_means(use_observed_outcome_meansSEXP);
    rcpp_result_gen = Rcpp::wrap(est_fgw_bipartite_match_outcome_diff_params_cpp(ome_xptr, stats_xptrs_by_cohort, outcome_idx_1, outcome_idx_2, observed_outcome_indices_list, use_observed_outcome_means));
    return rcpp_result_gen;
END_RCPP
}
// est_fgw_bipartite_match_outcome_diff_params_by_spec_multi_cpp
Rcpp::List est_fgw_bipartite_match_outcome_diff_params_by_spec_multi_cpp(Rcpp::List ome_by_spec, Rcpp::Nullable<Rcpp::List> stats_xptrs_by_cohort, Rcpp::IntegerVector outcome_indices_1, Rcpp::IntegerVector outcome_indices_2, Rcpp::List observed_outcome_indices_list, Rcpp::Nullable<Rcpp::NumericVector> outcome_weights, bool use_observed_outcome_means);
RcppExport SEXP _apm_est_fgw_bipartite_match_outcome_diff_params_by_spec_multi_cpp(SEXP ome_by_specSEXP, SEXP stats_xptrs_by_cohortSEXP, SEXP outcome_indices_1SEXP, SEXP outcome_indices_2SEXP, SEXP observed_outcome_indices_listSEXP, SEXP outcome_weightsSEXP, SEXP use_observed_outcome_meansSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type ome_by_spec(ome_by_specSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type stats_xptrs_by_cohort(stats_xptrs_by_cohortSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type outcome_indices_1(outcome_indices_1SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type outcome_indices_2(outcome_indices_2SEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices_list(observed_outcome_indices_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type outcome_weights(outcome_weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_observed_outcome_means(use_observed_outcome_meansSEXP);
    rcpp_result_gen = Rcpp::wrap(est_fgw_bipartite_match_outcome_diff_params_by_spec_multi_cpp(ome_by_spec, stats_xptrs_by_cohort, outcome_indices_1, outcome_indices_2, observed_outcome_indices_list, outcome_weights, use_observed_outcome_means));
    return rcpp_result_gen;
END_RCPP
}
// est_fgw_bipartite_match_outcome_diff_params_by_spec_cpp
Rcpp::List est_fgw_bipartite_match_outcome_diff_params_by_spec_cpp(Rcpp::List ome_by_spec, Rcpp::Nullable<Rcpp::List> stats_xptrs_by_cohort, int outcome_idx_1, int outcome_idx_2, Rcpp::List observed_outcome_indices_list, bool use_observed_outcome_means);
RcppExport SEXP _apm_est_fgw_bipartite_match_outcome_diff_params_by_spec_cpp(SEXP ome_by_specSEXP, SEXP stats_xptrs_by_cohortSEXP, SEXP outcome_idx_1SEXP, SEXP outcome_idx_2SEXP, SEXP observed_outcome_indices_listSEXP, SEXP use_observed_outcome_meansSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type ome_by_spec(ome_by_specSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type stats_xptrs_by_cohort(stats_xptrs_by_cohortSEXP);
    Rcpp::traits::input_parameter< int >::type outcome_idx_1(outcome_idx_1SEXP);
    Rcpp::traits::input_parameter< int >::type outcome_idx_2(outcome_idx_2SEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices_list(observed_outcome_indices_listSEXP);
    Rcpp::traits::input_parameter< bool >::type use_observed_outcome_means(use_observed_outcome_meansSEXP);
    rcpp_result_gen = Rcpp::wrap(est_fgw_bipartite_match_outcome_diff_params_by_spec_cpp(ome_by_spec, stats_xptrs_by_cohort, outcome_idx_1, outcome_idx_2, observed_outcome_indices_list, use_observed_outcome_means));
    return rcpp_result_gen;
END_RCPP
}
// est_avg_fgw_bipartite_match_outcome_diff_params_multi_cpp
SEXP est_avg_fgw_bipartite_match_outcome_diff_params_multi_cpp(SEXP ome_xptr, Rcpp::Nullable<Rcpp::List> stats_xptrs_by_cohort, Rcpp::List outcome_groupings, Rcpp::List observed_outcome_indices_list, Rcpp::Nullable<Rcpp::NumericVector> outcome_weights, bool use_observed_outcome_means, int num_threads);
RcppExport SEXP _apm_est_avg_fgw_bipartite_match_outcome_diff_params_multi_cpp(SEXP ome_xptrSEXP, SEXP stats_xptrs_by_cohortSEXP, SEXP outcome_groupingsSEXP, SEXP observed_outcome_indices_listSEXP, SEXP outcome_weightsSEXP, SEXP use_observed_outcome_meansSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ome_xptr(ome_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type stats_xptrs_by_cohort(stats_xptrs_by_cohortSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type outcome_groupings(outcome_groupingsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices_list(observed_outcome_indices_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type outcome_weights(outcome_weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_observed_outcome_means(use_observed_outcome_meansSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(est_avg_fgw_bipartite_match_outcome_diff_params_multi_cpp(ome_xptr, stats_xptrs_by_cohort, outcome_groupings, observed_outcome_indices_list, outcome_weights, use_observed_outcome_means, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// est_avg_fgw_bipartite_match_outcome_diff_params_cpp
SEXP est_avg_fgw_bipartite_match_outcome_diff_params_cpp(SEXP ome_xptr, Rcpp::Nullable<Rcpp::List> stats_xptrs_by_cohort, Rcpp::IntegerVector outcome_indices, Rcpp::List observed_outcome_indices_list, Rcpp::Nullable<Rcpp::NumericVector> outcome_weights, bool use_observed_outcome_means, int num_threads);
RcppExport SEXP _apm_est_avg_fgw_bipartite_match_outcome_diff_params_cpp(SEXP ome_xptrSEXP, SEXP stats_xptrs_by_cohortSEXP, SEXP outcome_indicesSEXP, SEXP observed_outcome_indices_listSEXP, SEXP outcome_weightsSEXP, SEXP use_observed_outcome_meansSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ome_xptr(ome_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type stats_xptrs_by_cohort(stats_xptrs_by_cohortSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type outcome_indices(outcome_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices_list(observed_outcome_indices_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type outcome_weights(outcome_weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_observed_outcome_means(use_observed_outcome_meansSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(est_avg_fgw_bipartite_match_outcome_diff_params_cpp(ome_xptr, stats_xptrs_by_cohort, outcome_indices, observed_outcome_indices_list, outcome_weights, use_observed_outcome_means, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// est_avg_fgw_bipartite_match_outcome_diff_params_by_spec_multi_cpp
Rcpp::List est_avg_fgw_bipartite_match_outcome_diff_params_by_spec_multi_cpp(Rcpp::List ome_by_spec, Rcpp::Nullable<Rcpp::List> stats_xptrs_by_cohort, Rcpp::List outcome_groupings, Rcpp::List observed_outcome_indices_list, Rcpp::Nullable<Rcpp::NumericVector> outcome_weights, bool use_observed_outcome_means, int num_threads);
RcppExport SEXP _apm_est_avg_fgw_bipartite_match_outcome_diff_params_by_spec_multi_cpp(SEXP ome_by_specSEXP, SEXP stats_xptrs_by_cohortSEXP, SEXP outcome_groupingsSEXP, SEXP observed_outcome_indices_listSEXP, SEXP outcome_weightsSEXP, SEXP use_observed_outcome_meansSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type ome_by_spec(ome_by_specSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type stats_xptrs_by_cohort(stats_xptrs_by_cohortSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type outcome_groupings(outcome_groupingsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices_list(observed_outcome_indices_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type outcome_weights(outcome_weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_observed_outcome_means(use_observed_outcome_meansSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(est_avg_fgw_bipartite_match_outcome_diff_params_by_spec_multi_cpp(ome_by_spec, stats_xptrs_by_cohort, outcome_groupings, observed_outcome_indices_list, outcome_weights, use_observed_outcome_means, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// est_avg_fgw_bipartite_match_outcome_diff_params_by_spec_cpp
Rcpp::List est_avg_fgw_bipartite_match_outcome_diff_params_by_spec_cpp(Rcpp::List ome_by_spec, Rcpp::Nullable<Rcpp::List> stats_xptrs_by_cohort, Rcpp::IntegerVector outcome_indices, Rcpp::List observed_outcome_indices_list, Rcpp::Nullable<Rcpp::NumericVector> outcome_weights, bool use_observed_outcome_means, int num_threads);
RcppExport SEXP _apm_est_avg_fgw_bipartite_match_outcome_diff_params_by_spec_cpp(SEXP ome_by_specSEXP, SEXP stats_xptrs_by_cohortSEXP, SEXP outcome_indicesSEXP, SEXP observed_outcome_indices_listSEXP, SEXP outcome_weightsSEXP, SEXP use_observed_outcome_meansSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type ome_by_spec(ome_by_specSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type stats_xptrs_by_cohort(stats_xptrs_by_cohortSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type outcome_indices(outcome_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices_list(observed_outcome_indices_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type outcome_weights(outcome_weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_observed_outcome_means(use_observed_outcome_meansSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(est_avg_fgw_bipartite_match_outcome_diff_params_by_spec_cpp(ome_by_spec, stats_xptrs_by_cohort, outcome_indices, observed_outcome_indices_list, outcome_weights, use_observed_outcome_means, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// caux_point_dims_cpp
Rcpp::IntegerVector caux_point_dims_cpp(SEXP xp_);
RcppExport SEXP _apm_caux_point_dims_cpp(SEXP xp_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp_(xp_SEXP);
    rcpp_result_gen = Rcpp::wrap(caux_point_dims_cpp(xp_));
    return rcpp_result_gen;
END_RCPP
}
// caux_point_aux_means_cpp
Rcpp::NumericMatrix caux_point_aux_means_cpp(SEXP xp_);
RcppExport SEXP _apm_caux_point_aux_means_cpp(SEXP xp_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp_(xp_SEXP);
    rcpp_result_gen = Rcpp::wrap(caux_point_aux_means_cpp(xp_));
    return rcpp_result_gen;
END_RCPP
}
// caux_has_bootstrap_cpp
bool caux_has_bootstrap_cpp(SEXP xp_);
RcppExport SEXP _apm_caux_has_bootstrap_cpp(SEXP xp_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp_(xp_SEXP);
    rcpp_result_gen = Rcpp::wrap(caux_has_bootstrap_cpp(xp_));
    return rcpp_result_gen;
END_RCPP
}
// caux_num_bootstrap_cpp
int caux_num_bootstrap_cpp(SEXP xp_);
RcppExport SEXP _apm_caux_num_bootstrap_cpp(SEXP xp_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp_(xp_SEXP);
    rcpp_result_gen = Rcpp::wrap(caux_num_bootstrap_cpp(xp_));
    return rcpp_result_gen;
END_RCPP
}
// caux_boot_aux_means_cpp
Rcpp::NumericMatrix caux_boot_aux_means_cpp(SEXP xp_, int b);
RcppExport SEXP _apm_caux_boot_aux_means_cpp(SEXP xp_SEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp_(xp_SEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(caux_boot_aux_means_cpp(xp_, b));
    return rcpp_result_gen;
END_RCPP
}
// comp_outcome_clustering_cpp
Rcpp::IntegerVector comp_outcome_clustering_cpp(SEXP panel_holder_xptr, int grid_size, int k, Rcpp::Nullable<Rcpp::IntegerVector> n_inits_in, Rcpp::Nullable<Rcpp::NumericVector> seed_in, Rcpp::Nullable<Rcpp::IntegerVector> num_threads_in);
RcppExport SEXP _apm_comp_outcome_clustering_cpp(SEXP panel_holder_xptrSEXP, SEXP grid_sizeSEXP, SEXP kSEXP, SEXP n_inits_inSEXP, SEXP seed_inSEXP, SEXP num_threads_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type panel_holder_xptr(panel_holder_xptrSEXP);
    Rcpp::traits::input_parameter< int >::type grid_size(grid_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type n_inits_in(n_inits_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type seed_in(seed_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type num_threads_in(num_threads_inSEXP);
    rcpp_result_gen = Rcpp::wrap(comp_outcome_clustering_cpp(panel_holder_xptr, grid_size, k, n_inits_in, seed_in, num_threads_in));
    return rcpp_result_gen;
END_RCPP
}
// comp_outcome_clusterings_cpp
Rcpp::IntegerMatrix comp_outcome_clusterings_cpp(SEXP panel_holder_xptr, int grid_size, int min_k, int max_k, Rcpp::Nullable<Rcpp::IntegerVector> n_inits_in, Rcpp::Nullable<Rcpp::NumericVector> seed_in, Rcpp::Nullable<Rcpp::IntegerVector> num_threads_in);
RcppExport SEXP _apm_comp_outcome_clusterings_cpp(SEXP panel_holder_xptrSEXP, SEXP grid_sizeSEXP, SEXP min_kSEXP, SEXP max_kSEXP, SEXP n_inits_inSEXP, SEXP seed_inSEXP, SEXP num_threads_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type panel_holder_xptr(panel_holder_xptrSEXP);
    Rcpp::traits::input_parameter< int >::type grid_size(grid_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type min_k(min_kSEXP);
    Rcpp::traits::input_parameter< int >::type max_k(max_kSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type n_inits_in(n_inits_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type seed_in(seed_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type num_threads_in(num_threads_inSEXP);
    rcpp_result_gen = Rcpp::wrap(comp_outcome_clusterings_cpp(panel_holder_xptr, grid_size, min_k, max_k, n_inits_in, seed_in, num_threads_in));
    return rcpp_result_gen;
END_RCPP
}
// get_new_cohorts_from_combining_outcomes_cpp
Rcpp::List get_new_cohorts_from_combining_outcomes_cpp(SEXP panel_holder_xptr, Rcpp::IntegerVector old_to_new_outcome_1b);
RcppExport SEXP _apm_get_new_cohorts_from_combining_outcomes_cpp(SEXP panel_holder_xptrSEXP, SEXP old_to_new_outcome_1bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type panel_holder_xptr(panel_holder_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type old_to_new_outcome_1b(old_to_new_outcome_1bSEXP);
    rcpp_result_gen = Rcpp::wrap(get_new_cohorts_from_combining_outcomes_cpp(panel_holder_xptr, old_to_new_outcome_1b));
    return rcpp_result_gen;
END_RCPP
}
// comp_imputation_components_cpp
SEXP comp_imputation_components_cpp(SEXP panel_holder_xptr, SEXP factor_model_estimates_xptr, Rcpp::Nullable<Rcpp::List> cohort_outcome_mean_suff_stat_ests, SEXP weighted_bootstrap_xptr, Rcpp::Nullable<Rcpp::List> effective_observed_outcome_indices, Rcpp::Nullable<Rcpp::List> imputation_options_in, Rcpp::Nullable<Rcpp::IntegerVector> num_threads_in);
RcppExport SEXP _apm_comp_imputation_components_cpp(SEXP panel_holder_xptrSEXP, SEXP factor_model_estimates_xptrSEXP, SEXP cohort_outcome_mean_suff_stat_estsSEXP, SEXP weighted_bootstrap_xptrSEXP, SEXP effective_observed_outcome_indicesSEXP, SEXP imputation_options_inSEXP, SEXP num_threads_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type panel_holder_xptr(panel_holder_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type factor_model_estimates_xptr(factor_model_estimates_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type cohort_outcome_mean_suff_stat_ests(cohort_outcome_mean_suff_stat_estsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type weighted_bootstrap_xptr(weighted_bootstrap_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type effective_observed_outcome_indices(effective_observed_outcome_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type imputation_options_in(imputation_options_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type num_threads_in(num_threads_inSEXP);
    rcpp_result_gen = Rcpp::wrap(comp_imputation_components_cpp(panel_holder_xptr, factor_model_estimates_xptr, cohort_outcome_mean_suff_stat_ests, weighted_bootstrap_xptr, effective_observed_outcome_indices, imputation_options_in, num_threads_in));
    return rcpp_result_gen;
END_RCPP
}
// comp_imputation_components_by_spec_cpp
Rcpp::List comp_imputation_components_by_spec_cpp(SEXP panel_holder_xptr, Rcpp::List factor_model_estimates_by_spec, Rcpp::Nullable<Rcpp::List> cohort_outcome_mean_suff_stat_ests, SEXP weighted_bootstrap_xptr, Rcpp::Nullable<Rcpp::List> effective_observed_outcome_indices, Rcpp::Nullable<Rcpp::List> imputation_options_in, Rcpp::Nullable<Rcpp::IntegerVector> num_threads_in);
RcppExport SEXP _apm_comp_imputation_components_by_spec_cpp(SEXP panel_holder_xptrSEXP, SEXP factor_model_estimates_by_specSEXP, SEXP cohort_outcome_mean_suff_stat_estsSEXP, SEXP weighted_bootstrap_xptrSEXP, SEXP effective_observed_outcome_indicesSEXP, SEXP imputation_options_inSEXP, SEXP num_threads_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type panel_holder_xptr(panel_holder_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type factor_model_estimates_by_spec(factor_model_estimates_by_specSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type cohort_outcome_mean_suff_stat_ests(cohort_outcome_mean_suff_stat_estsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type weighted_bootstrap_xptr(weighted_bootstrap_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type effective_observed_outcome_indices(effective_observed_outcome_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type imputation_options_in(imputation_options_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type num_threads_in(num_threads_inSEXP);
    rcpp_result_gen = Rcpp::wrap(comp_imputation_components_by_spec_cpp(panel_holder_xptr, factor_model_estimates_by_spec, cohort_outcome_mean_suff_stat_ests, weighted_bootstrap_xptr, effective_observed_outcome_indices, imputation_options_in, num_threads_in));
    return rcpp_result_gen;
END_RCPP
}
// outcome_mean_estimator_new_cpp
SEXP outcome_mean_estimator_new_cpp(std::size_t T_c, SEXP wb_xptr, std::size_t T, std::size_t q);
RcppExport SEXP _apm_outcome_mean_estimator_new_cpp(SEXP T_cSEXP, SEXP wb_xptrSEXP, SEXP TSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::size_t >::type T_c(T_cSEXP);
    Rcpp::traits::input_parameter< SEXP >::type wb_xptr(wb_xptrSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type T(TSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(outcome_mean_estimator_new_cpp(T_c, wb_xptr, T, q));
    return rcpp_result_gen;
END_RCPP
}
// omsse_add_data_cpp
void omsse_add_data_cpp(SEXP xp, arma::uvec unit_idxs_1based, const arma::mat& Y, Rcpp::Nullable<arma::cube> X);
RcppExport SEXP _apm_omsse_add_data_cpp(SEXP xpSEXP, SEXP unit_idxs_1basedSEXP, SEXP YSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type unit_idxs_1based(unit_idxs_1basedSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::cube> >::type X(XSEXP);
    omsse_add_data_cpp(xp, unit_idxs_1based, Y, X);
    return R_NilValue;
END_RCPP
}
// omsse_add_datum_cpp
void omsse_add_datum_cpp(SEXP xp, std::size_t unit_idx_1based, const arma::vec& Y, Rcpp::Nullable<arma::mat> X);
RcppExport SEXP _apm_omsse_add_datum_cpp(SEXP xpSEXP, SEXP unit_idx_1basedSEXP, SEXP YSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type unit_idx_1based(unit_idx_1basedSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type X(XSEXP);
    omsse_add_datum_cpp(xp, unit_idx_1based, Y, X);
    return R_NilValue;
END_RCPP
}
// omsse_Tc_cpp
std::size_t omsse_Tc_cpp(SEXP xp);
RcppExport SEXP _apm_omsse_Tc_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_Tc_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// omsse_T_cpp
std::size_t omsse_T_cpp(SEXP xp);
RcppExport SEXP _apm_omsse_T_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_T_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// omsse_q_cpp
std::size_t omsse_q_cpp(SEXP xp);
RcppExport SEXP _apm_omsse_q_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_q_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// omsse_B_cpp
std::size_t omsse_B_cpp(SEXP xp);
RcppExport SEXP _apm_omsse_B_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_B_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// omsse_estimate_cpp
SEXP omsse_estimate_cpp(SEXP xp);
RcppExport SEXP _apm_omsse_estimate_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_estimate_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// omsse_estimate_with_total_cpp
SEXP omsse_estimate_with_total_cpp(SEXP xp, std::size_t total_units);
RcppExport SEXP _apm_omsse_estimate_with_total_cpp(SEXP xpSEXP, SEXP total_unitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type total_units(total_unitsSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_estimate_with_total_cpp(xp, total_units));
    return rcpp_result_gen;
END_RCPP
}
// omsse_has_bootstrap_cpp
bool omsse_has_bootstrap_cpp(SEXP xp);
RcppExport SEXP _apm_omsse_has_bootstrap_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_has_bootstrap_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// omsse_num_bootstrap_cpp
std::size_t omsse_num_bootstrap_cpp(SEXP xp);
RcppExport SEXP _apm_omsse_num_bootstrap_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_num_bootstrap_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// omsse_point_has_covar_means_cpp
bool omsse_point_has_covar_means_cpp(SEXP xp);
RcppExport SEXP _apm_omsse_point_has_covar_means_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_point_has_covar_means_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// omsse_point_Tc_cpp
std::size_t omsse_point_Tc_cpp(SEXP xp);
RcppExport SEXP _apm_omsse_point_Tc_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_point_Tc_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// omsse_point_T_cpp
std::size_t omsse_point_T_cpp(SEXP xp);
RcppExport SEXP _apm_omsse_point_T_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_point_T_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// omsse_point_q_cpp
std::size_t omsse_point_q_cpp(SEXP xp);
RcppExport SEXP _apm_omsse_point_q_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_point_q_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// omsse_point_observed_means_cpp
arma::vec omsse_point_observed_means_cpp(SEXP xp);
RcppExport SEXP _apm_omsse_point_observed_means_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_point_observed_means_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// omsse_point_covar_means_cpp
arma::mat omsse_point_covar_means_cpp(SEXP xp);
RcppExport SEXP _apm_omsse_point_covar_means_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_point_covar_means_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// omsse_point_cohort_pop_share_cpp
double omsse_point_cohort_pop_share_cpp(SEXP xp);
RcppExport SEXP _apm_omsse_point_cohort_pop_share_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_point_cohort_pop_share_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// omsse_boot_cohort_pop_share_cpp
double omsse_boot_cohort_pop_share_cpp(SEXP xp, std::size_t b);
RcppExport SEXP _apm_omsse_boot_cohort_pop_share_cpp(SEXP xpSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_boot_cohort_pop_share_cpp(xp, b));
    return rcpp_result_gen;
END_RCPP
}
// omsse_boot_observed_means_cpp
arma::vec omsse_boot_observed_means_cpp(SEXP xp, std::size_t b);
RcppExport SEXP _apm_omsse_boot_observed_means_cpp(SEXP xpSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_boot_observed_means_cpp(xp, b));
    return rcpp_result_gen;
END_RCPP
}
// omsse_boot_covar_means_cpp
arma::mat omsse_boot_covar_means_cpp(SEXP xp, std::size_t b);
RcppExport SEXP _apm_omsse_boot_covar_means_cpp(SEXP xpSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(omsse_boot_covar_means_cpp(xp, b));
    return rcpp_result_gen;
END_RCPP
}
// ome_has_bootstrap_cpp
bool ome_has_bootstrap_cpp(SEXP xp);
RcppExport SEXP _apm_ome_has_bootstrap_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(ome_has_bootstrap_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// ome_num_bootstrap_cpp
int ome_num_bootstrap_cpp(SEXP xp);
RcppExport SEXP _apm_ome_num_bootstrap_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(ome_num_bootstrap_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// ome_point_means_cpp
Rcpp::NumericMatrix ome_point_means_cpp(SEXP xp);
RcppExport SEXP _apm_ome_point_means_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(ome_point_means_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// ome_boot_means_cpp
Rcpp::NumericMatrix ome_boot_means_cpp(SEXP xp, int b1);
RcppExport SEXP _apm_ome_boot_means_cpp(SEXP xpSEXP, SEXP b1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< int >::type b1(b1SEXP);
    rcpp_result_gen = Rcpp::wrap(ome_boot_means_cpp(xp, b1));
    return rcpp_result_gen;
END_RCPP
}
// ome_C_cpp
int ome_C_cpp(SEXP xp);
RcppExport SEXP _apm_ome_C_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(ome_C_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// ome_T_cpp
int ome_T_cpp(SEXP xp);
RcppExport SEXP _apm_ome_T_cpp(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(ome_T_cpp(xp));
    return rcpp_result_gen;
END_RCPP
}
// pc_estimator_new_cpp
SEXP pc_estimator_new_cpp(std::size_t r, std::size_t T_c, SEXP wb_xptr, std::size_t q);
RcppExport SEXP _apm_pc_estimator_new_cpp(SEXP rSEXP, SEXP T_cSEXP, SEXP wb_xptrSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::size_t >::type r(rSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type T_c(T_cSEXP);
    Rcpp::traits::input_parameter< SEXP >::type wb_xptr(wb_xptrSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(pc_estimator_new_cpp(r, T_c, wb_xptr, q));
    return rcpp_result_gen;
END_RCPP
}
// pc_fe_estimator_new_cpp
SEXP pc_fe_estimator_new_cpp(std::size_t r, std::size_t T_c, SEXP wb_xptr, std::size_t q);
RcppExport SEXP _apm_pc_fe_estimator_new_cpp(SEXP rSEXP, SEXP T_cSEXP, SEXP wb_xptrSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::size_t >::type r(rSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type T_c(T_cSEXP);
    Rcpp::traits::input_parameter< SEXP >::type wb_xptr(wb_xptrSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(pc_fe_estimator_new_cpp(r, T_c, wb_xptr, q));
    return rcpp_result_gen;
END_RCPP
}
// aligned_factors_identified
bool aligned_factors_identified(Rcpp::List observed_outcome_indices, unsigned int r);
RcppExport SEXP _apm_aligned_factors_identified(SEXP observed_outcome_indicesSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices(observed_outcome_indicesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(aligned_factors_identified(observed_outcome_indices, r));
    return rcpp_result_gen;
END_RCPP
}
// get_largest_super_cohort
arma::uvec get_largest_super_cohort(Rcpp::List observed_outcome_indices, const arma::uvec& cohort_sizes, std::size_t max_model_rank, Rcpp::Nullable<Rcpp::IntegerVector> iter);
RcppExport SEXP _apm_get_largest_super_cohort(SEXP observed_outcome_indicesSEXP, SEXP cohort_sizesSEXP, SEXP max_model_rankSEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices(observed_outcome_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type cohort_sizes(cohort_sizesSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type max_model_rank(max_model_rankSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type iter(iterSEXP);
    rcpp_result_gen = Rcpp::wrap(get_largest_super_cohort(observed_outcome_indices, cohort_sizes, max_model_rank, iter));
    return rcpp_result_gen;
END_RCPP
}
// summarize_identification_cpp
Rcpp::List summarize_identification_cpp(Rcpp::List observed_outcome_indices, const arma::uvec& cohort_sizes, std::size_t max_model_rank, Rcpp::Nullable<Rcpp::IntegerVector> iter, Rcpp::Nullable<Rcpp::NumericVector> outcome_weights);
RcppExport SEXP _apm_summarize_identification_cpp(SEXP observed_outcome_indicesSEXP, SEXP cohort_sizesSEXP, SEXP max_model_rankSEXP, SEXP iterSEXP, SEXP outcome_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices(observed_outcome_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type cohort_sizes(cohort_sizesSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type max_model_rank(max_model_rankSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type outcome_weights(outcome_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(summarize_identification_cpp(observed_outcome_indices, cohort_sizes, max_model_rank, iter, outcome_weights));
    return rcpp_result_gen;
END_RCPP
}
// summarize_identification_many_cpp
Rcpp::List summarize_identification_many_cpp(Rcpp::List observed_outcome_indices_list, Rcpp::List cohort_sizes_list, std::size_t max_model_rank, Rcpp::Nullable<Rcpp::IntegerVector> iter, Rcpp::Nullable<Rcpp::List> outcome_weights_list);
RcppExport SEXP _apm_summarize_identification_many_cpp(SEXP observed_outcome_indices_listSEXP, SEXP cohort_sizes_listSEXP, SEXP max_model_rankSEXP, SEXP iterSEXP, SEXP outcome_weights_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices_list(observed_outcome_indices_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cohort_sizes_list(cohort_sizes_listSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type max_model_rank(max_model_rankSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type outcome_weights_list(outcome_weights_listSEXP);
    rcpp_result_gen = Rcpp::wrap(summarize_identification_many_cpp(observed_outcome_indices_list, cohort_sizes_list, max_model_rank, iter, outcome_weights_list));
    return rcpp_result_gen;
END_RCPP
}
// count_outcomes_with_rank_overlap_per_cohort
arma::vec count_outcomes_with_rank_overlap_per_cohort(Rcpp::List observed_outcome_indices, std::size_t rank, Rcpp::Nullable<Rcpp::NumericVector> outcome_weights);
RcppExport SEXP _apm_count_outcomes_with_rank_overlap_per_cohort(SEXP observed_outcome_indicesSEXP, SEXP rankSEXP, SEXP outcome_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices(observed_outcome_indicesSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type rank(rankSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type outcome_weights(outcome_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(count_outcomes_with_rank_overlap_per_cohort(observed_outcome_indices, rank, outcome_weights));
    return rcpp_result_gen;
END_RCPP
}
// get_masked_observed_outcome_indices
Rcpp::List get_masked_observed_outcome_indices(Rcpp::List observed_outcome_indices, Rcpp::Nullable<Rcpp::List> cohort_outcomes_to_mask_in);
RcppExport SEXP _apm_get_masked_observed_outcome_indices(SEXP observed_outcome_indicesSEXP, SEXP cohort_outcomes_to_mask_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type observed_outcome_indices(observed_outcome_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type cohort_outcomes_to_mask_in(cohort_outcomes_to_mask_inSEXP);
    rcpp_result_gen = Rcpp::wrap(get_masked_observed_outcome_indices(observed_outcome_indices, cohort_outcomes_to_mask_in));
    return rcpp_result_gen;
END_RCPP
}
// twfe_estimator_new_cpp
SEXP twfe_estimator_new_cpp(std::size_t T_c, SEXP wb_xptr, std::size_t q);
RcppExport SEXP _apm_twfe_estimator_new_cpp(SEXP T_cSEXP, SEXP wb_xptrSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::size_t >::type T_c(T_cSEXP);
    Rcpp::traits::input_parameter< SEXP >::type wb_xptr(wb_xptrSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(twfe_estimator_new_cpp(T_c, wb_xptr, q));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_apm_aggregate_factor_model_params_cpp", (DL_FUNC) &_apm_aggregate_factor_model_params_cpp, 3},
    {"_apm_aggregate_factor_model_params_by_spec_cpp", (DL_FUNC) &_apm_aggregate_factor_model_params_by_spec_cpp, 3},
    {"_apm_get_version", (DL_FUNC) &_apm_get_version, 0},
    {"_apm_align_factors_using_apm", (DL_FUNC) &_apm_align_factors_using_apm, 3},
    {"_apm_compute_aggregated_projection_matrix", (DL_FUNC) &_apm_compute_aggregated_projection_matrix, 3},
    {"_apm_aggregate_cohort_specific_covariate_coefs", (DL_FUNC) &_apm_aggregate_cohort_specific_covariate_coefs, 1},
    {"_apm_aggregate_cohort_specific_outcome_fes", (DL_FUNC) &_apm_aggregate_cohort_specific_outcome_fes, 2},
    {"_apm_impute_outcomes_from_obs_outcomes", (DL_FUNC) &_apm_impute_outcomes_from_obs_outcomes, 6},
    {"_apm_impute_outcomes_across_cohorts_from_obs_outcomes", (DL_FUNC) &_apm_impute_outcomes_across_cohorts_from_obs_outcomes, 6},
    {"_apm_o3_algorithm", (DL_FUNC) &_apm_o3_algorithm, 2},
    {"_apm_impute_outcomes_across_cohorts", (DL_FUNC) &_apm_impute_outcomes_across_cohorts, 5},
    {"_apm_get_weighted_bootstrap_ptr_cpp", (DL_FUNC) &_apm_get_weighted_bootstrap_ptr_cpp, 4},
    {"_apm_wb_n_obs_cpp", (DL_FUNC) &_apm_wb_n_obs_cpp, 1},
    {"_apm_wb_n_bootstraps_cpp", (DL_FUNC) &_apm_wb_n_bootstraps_cpp, 1},
    {"_apm_wb_draw_cpp", (DL_FUNC) &_apm_wb_draw_cpp, 2},
    {"_apm_wb_obs_cpp", (DL_FUNC) &_apm_wb_obs_cpp, 2},
    {"_apm_wb_obs_rows_cpp", (DL_FUNC) &_apm_wb_obs_rows_cpp, 2},
    {"_apm_wb_weights_cpp", (DL_FUNC) &_apm_wb_weights_cpp, 1},
    {"_apm_get_bootstrap_inference_cpp", (DL_FUNC) &_apm_get_bootstrap_inference_cpp, 4},
    {"_apm_sir_point_cpp", (DL_FUNC) &_apm_sir_point_cpp, 1},
    {"_apm_sir_pointwise_t_cpp", (DL_FUNC) &_apm_sir_pointwise_t_cpp, 1},
    {"_apm_sir_pointwise_p_cpp", (DL_FUNC) &_apm_sir_pointwise_p_cpp, 1},
    {"_apm_sir_std_error_cpp", (DL_FUNC) &_apm_sir_std_error_cpp, 1},
    {"_apm_sir_sig_level_cpp", (DL_FUNC) &_apm_sir_sig_level_cpp, 1},
    {"_apm_sir_ci_lb_cpp", (DL_FUNC) &_apm_sir_ci_lb_cpp, 1},
    {"_apm_sir_ci_ub_cpp", (DL_FUNC) &_apm_sir_ci_ub_cpp, 1},
    {"_apm_sir_fwer_control_p_cpp", (DL_FUNC) &_apm_sir_fwer_control_p_cpp, 1},
    {"_apm_sir_cb_lb_cpp", (DL_FUNC) &_apm_sir_cb_lb_cpp, 1},
    {"_apm_sir_cb_ub_cpp", (DL_FUNC) &_apm_sir_cb_ub_cpp, 1},
    {"_apm_cwe_has_bootstrap_cpp", (DL_FUNC) &_apm_cwe_has_bootstrap_cpp, 1},
    {"_apm_cwe_num_bootstrap_cpp", (DL_FUNC) &_apm_cwe_num_bootstrap_cpp, 1},
    {"_apm_cwe_point_weights_cpp", (DL_FUNC) &_apm_cwe_point_weights_cpp, 1},
    {"_apm_cwe_boot_weights_cpp", (DL_FUNC) &_apm_cwe_boot_weights_cpp, 2},
    {"_apm_build_R_panel_holder_cpp", (DL_FUNC) &_apm_build_R_panel_holder_cpp, 6},
    {"_apm_est_cohort_specific_params_from_panel_cpp", (DL_FUNC) &_apm_est_cohort_specific_params_from_panel_cpp, 5},
    {"_apm_est_masked_outcome_mean_err_metrics_cpp", (DL_FUNC) &_apm_est_masked_outcome_mean_err_metrics_cpp, 1},
    {"_apm_estimate_outcome_means_across_cohorts_cpp", (DL_FUNC) &_apm_estimate_outcome_means_across_cohorts_cpp, 3},
    {"_apm_estimate_outcome_means_across_cohorts_by_spec_cpp", (DL_FUNC) &_apm_estimate_outcome_means_across_cohorts_by_spec_cpp, 3},
    {"_apm_get_cpp_default_concurrency", (DL_FUNC) &_apm_get_cpp_default_concurrency, 0},
    {"_apm_make_factor_model_estimates_cpp", (DL_FUNC) &_apm_make_factor_model_estimates_cpp, 4},
    {"_apm_make_outcome_mean_suff_stat_estimates_cpp", (DL_FUNC) &_apm_make_outcome_mean_suff_stat_estimates_cpp, 3},
    {"_apm_make_cohort_weight_estimates_cpp", (DL_FUNC) &_apm_make_cohort_weight_estimates_cpp, 2},
    {"_apm_est_target_params_cpp", (DL_FUNC) &_apm_est_target_params_cpp, 4},
    {"_apm_tpe_has_bootstrap_cpp", (DL_FUNC) &_apm_tpe_has_bootstrap_cpp, 1},
    {"_apm_tpe_num_bootstrap_cpp", (DL_FUNC) &_apm_tpe_num_bootstrap_cpp, 1},
    {"_apm_tpe_p_cpp", (DL_FUNC) &_apm_tpe_p_cpp, 1},
    {"_apm_tpe_point_params_cpp", (DL_FUNC) &_apm_tpe_point_params_cpp, 1},
    {"_apm_tpe_boot_params_cpp", (DL_FUNC) &_apm_tpe_boot_params_cpp, 2},
    {"_apm_tpe_boot_params_matrix_cpp", (DL_FUNC) &_apm_tpe_boot_params_matrix_cpp, 1},
    {"_apm_est_target_params_by_spec_cpp", (DL_FUNC) &_apm_est_target_params_by_spec_cpp, 4},
    {"_apm_get_target_param_diff_ests_cpp", (DL_FUNC) &_apm_get_target_param_diff_ests_cpp, 2},
    {"_apm_combine_target_param_ests_cpp", (DL_FUNC) &_apm_combine_target_param_ests_cpp, 2},
    {"_apm_combine_target_param_ests_multi_cpp", (DL_FUNC) &_apm_combine_target_param_ests_multi_cpp, 1},
    {"_apm_subset_target_param_ests_cpp", (DL_FUNC) &_apm_subset_target_param_ests_cpp, 2},
    {"_apm_est_target_param_components_from_panel_cpp", (DL_FUNC) &_apm_est_target_param_components_from_panel_cpp, 7},
    {"_apm_target_param_inference_cpp", (DL_FUNC) &_apm_target_param_inference_cpp, 3},
    {"_apm_target_param_inference_by_spec_cpp", (DL_FUNC) &_apm_target_param_inference_by_spec_cpp, 3},
    {"_apm_estimator_add_data_cpp", (DL_FUNC) &_apm_estimator_add_data_cpp, 4},
    {"_apm_estimator_add_datum_cpp", (DL_FUNC) &_apm_estimator_add_datum_cpp, 4},
    {"_apm_estimator_r_cpp", (DL_FUNC) &_apm_estimator_r_cpp, 1},
    {"_apm_estimator_Tc_cpp", (DL_FUNC) &_apm_estimator_Tc_cpp, 1},
    {"_apm_estimator_q_cpp", (DL_FUNC) &_apm_estimator_q_cpp, 1},
    {"_apm_estimator_B_cpp", (DL_FUNC) &_apm_estimator_B_cpp, 1},
    {"_apm_estimator_estimate_cpp", (DL_FUNC) &_apm_estimator_estimate_cpp, 1},
    {"_apm_fme_has_bootstrap_cpp", (DL_FUNC) &_apm_fme_has_bootstrap_cpp, 1},
    {"_apm_fme_num_bootstrap_cpp", (DL_FUNC) &_apm_fme_num_bootstrap_cpp, 1},
    {"_apm_fme_has_g0_cpp", (DL_FUNC) &_apm_fme_has_g0_cpp, 1},
    {"_apm_fme_has_a_cpp", (DL_FUNC) &_apm_fme_has_a_cpp, 1},
    {"_apm_fme_point_G_cpp", (DL_FUNC) &_apm_fme_point_G_cpp, 1},
    {"_apm_fme_point_g0_cpp", (DL_FUNC) &_apm_fme_point_g0_cpp, 1},
    {"_apm_fme_point_a_cpp", (DL_FUNC) &_apm_fme_point_a_cpp, 1},
    {"_apm_fme_boot_G_cpp", (DL_FUNC) &_apm_fme_boot_G_cpp, 2},
    {"_apm_fme_boot_g0_cpp", (DL_FUNC) &_apm_fme_boot_g0_cpp, 2},
    {"_apm_fme_boot_a_cpp", (DL_FUNC) &_apm_fme_boot_a_cpp, 2},
    {"_apm_fme_point_L_cpp", (DL_FUNC) &_apm_fme_point_L_cpp, 1},
    {"_apm_fme_boot_L_cpp", (DL_FUNC) &_apm_fme_boot_L_cpp, 2},
    {"_apm_est_fgw_bipartite_match_outcome_diff_params_multi_cpp", (DL_FUNC) &_apm_est_fgw_bipartite_match_outcome_diff_params_multi_cpp, 7},
    {"_apm_est_fgw_bipartite_match_outcome_diff_params_cpp", (DL_FUNC) &_apm_est_fgw_bipartite_match_outcome_diff_params_cpp, 6},
    {"_apm_est_fgw_bipartite_match_outcome_diff_params_by_spec_multi_cpp", (DL_FUNC) &_apm_est_fgw_bipartite_match_outcome_diff_params_by_spec_multi_cpp, 7},
    {"_apm_est_fgw_bipartite_match_outcome_diff_params_by_spec_cpp", (DL_FUNC) &_apm_est_fgw_bipartite_match_outcome_diff_params_by_spec_cpp, 6},
    {"_apm_est_avg_fgw_bipartite_match_outcome_diff_params_multi_cpp", (DL_FUNC) &_apm_est_avg_fgw_bipartite_match_outcome_diff_params_multi_cpp, 7},
    {"_apm_est_avg_fgw_bipartite_match_outcome_diff_params_cpp", (DL_FUNC) &_apm_est_avg_fgw_bipartite_match_outcome_diff_params_cpp, 7},
    {"_apm_est_avg_fgw_bipartite_match_outcome_diff_params_by_spec_multi_cpp", (DL_FUNC) &_apm_est_avg_fgw_bipartite_match_outcome_diff_params_by_spec_multi_cpp, 7},
    {"_apm_est_avg_fgw_bipartite_match_outcome_diff_params_by_spec_cpp", (DL_FUNC) &_apm_est_avg_fgw_bipartite_match_outcome_diff_params_by_spec_cpp, 7},
    {"_apm_caux_point_dims_cpp", (DL_FUNC) &_apm_caux_point_dims_cpp, 1},
    {"_apm_caux_point_aux_means_cpp", (DL_FUNC) &_apm_caux_point_aux_means_cpp, 1},
    {"_apm_caux_has_bootstrap_cpp", (DL_FUNC) &_apm_caux_has_bootstrap_cpp, 1},
    {"_apm_caux_num_bootstrap_cpp", (DL_FUNC) &_apm_caux_num_bootstrap_cpp, 1},
    {"_apm_caux_boot_aux_means_cpp", (DL_FUNC) &_apm_caux_boot_aux_means_cpp, 2},
    {"_apm_comp_outcome_clustering_cpp", (DL_FUNC) &_apm_comp_outcome_clustering_cpp, 6},
    {"_apm_comp_outcome_clusterings_cpp", (DL_FUNC) &_apm_comp_outcome_clusterings_cpp, 7},
    {"_apm_get_new_cohorts_from_combining_outcomes_cpp", (DL_FUNC) &_apm_get_new_cohorts_from_combining_outcomes_cpp, 2},
    {"_apm_comp_imputation_components_cpp", (DL_FUNC) &_apm_comp_imputation_components_cpp, 7},
    {"_apm_comp_imputation_components_by_spec_cpp", (DL_FUNC) &_apm_comp_imputation_components_by_spec_cpp, 7},
    {"_apm_outcome_mean_estimator_new_cpp", (DL_FUNC) &_apm_outcome_mean_estimator_new_cpp, 4},
    {"_apm_omsse_add_data_cpp", (DL_FUNC) &_apm_omsse_add_data_cpp, 4},
    {"_apm_omsse_add_datum_cpp", (DL_FUNC) &_apm_omsse_add_datum_cpp, 4},
    {"_apm_omsse_Tc_cpp", (DL_FUNC) &_apm_omsse_Tc_cpp, 1},
    {"_apm_omsse_T_cpp", (DL_FUNC) &_apm_omsse_T_cpp, 1},
    {"_apm_omsse_q_cpp", (DL_FUNC) &_apm_omsse_q_cpp, 1},
    {"_apm_omsse_B_cpp", (DL_FUNC) &_apm_omsse_B_cpp, 1},
    {"_apm_omsse_estimate_cpp", (DL_FUNC) &_apm_omsse_estimate_cpp, 1},
    {"_apm_omsse_estimate_with_total_cpp", (DL_FUNC) &_apm_omsse_estimate_with_total_cpp, 2},
    {"_apm_omsse_has_bootstrap_cpp", (DL_FUNC) &_apm_omsse_has_bootstrap_cpp, 1},
    {"_apm_omsse_num_bootstrap_cpp", (DL_FUNC) &_apm_omsse_num_bootstrap_cpp, 1},
    {"_apm_omsse_point_has_covar_means_cpp", (DL_FUNC) &_apm_omsse_point_has_covar_means_cpp, 1},
    {"_apm_omsse_point_Tc_cpp", (DL_FUNC) &_apm_omsse_point_Tc_cpp, 1},
    {"_apm_omsse_point_T_cpp", (DL_FUNC) &_apm_omsse_point_T_cpp, 1},
    {"_apm_omsse_point_q_cpp", (DL_FUNC) &_apm_omsse_point_q_cpp, 1},
    {"_apm_omsse_point_observed_means_cpp", (DL_FUNC) &_apm_omsse_point_observed_means_cpp, 1},
    {"_apm_omsse_point_covar_means_cpp", (DL_FUNC) &_apm_omsse_point_covar_means_cpp, 1},
    {"_apm_omsse_point_cohort_pop_share_cpp", (DL_FUNC) &_apm_omsse_point_cohort_pop_share_cpp, 1},
    {"_apm_omsse_boot_cohort_pop_share_cpp", (DL_FUNC) &_apm_omsse_boot_cohort_pop_share_cpp, 2},
    {"_apm_omsse_boot_observed_means_cpp", (DL_FUNC) &_apm_omsse_boot_observed_means_cpp, 2},
    {"_apm_omsse_boot_covar_means_cpp", (DL_FUNC) &_apm_omsse_boot_covar_means_cpp, 2},
    {"_apm_ome_has_bootstrap_cpp", (DL_FUNC) &_apm_ome_has_bootstrap_cpp, 1},
    {"_apm_ome_num_bootstrap_cpp", (DL_FUNC) &_apm_ome_num_bootstrap_cpp, 1},
    {"_apm_ome_point_means_cpp", (DL_FUNC) &_apm_ome_point_means_cpp, 1},
    {"_apm_ome_boot_means_cpp", (DL_FUNC) &_apm_ome_boot_means_cpp, 2},
    {"_apm_ome_C_cpp", (DL_FUNC) &_apm_ome_C_cpp, 1},
    {"_apm_ome_T_cpp", (DL_FUNC) &_apm_ome_T_cpp, 1},
    {"_apm_pc_estimator_new_cpp", (DL_FUNC) &_apm_pc_estimator_new_cpp, 4},
    {"_apm_pc_fe_estimator_new_cpp", (DL_FUNC) &_apm_pc_fe_estimator_new_cpp, 4},
    {"_apm_aligned_factors_identified", (DL_FUNC) &_apm_aligned_factors_identified, 2},
    {"_apm_get_largest_super_cohort", (DL_FUNC) &_apm_get_largest_super_cohort, 4},
    {"_apm_summarize_identification_cpp", (DL_FUNC) &_apm_summarize_identification_cpp, 5},
    {"_apm_summarize_identification_many_cpp", (DL_FUNC) &_apm_summarize_identification_many_cpp, 5},
    {"_apm_count_outcomes_with_rank_overlap_per_cohort", (DL_FUNC) &_apm_count_outcomes_with_rank_overlap_per_cohort, 3},
    {"_apm_get_masked_observed_outcome_indices", (DL_FUNC) &_apm_get_masked_observed_outcome_indices, 2},
    {"_apm_twfe_estimator_new_cpp", (DL_FUNC) &_apm_twfe_estimator_new_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_apm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
